### ISSUE TITLE
I need Value Formatting & Validation

### ISSUE THREAD

**Issue by ajoslin103** [dohomi/react-hook-form-mui#10]
Hi,

I need Value Formatting & Validation

If they don't work already somehow I'll try to add them and submit a PR

thanks

**Comment by dohomi** [comment]
@ajoslin103 validation is built in. the `required` prop works out of the box, anything more complex you can drop in with the `validation` prop which is https://github.com/dohomi/react-hook-form-mui/blob/master/src/TextFieldElement.tsx#L7 same as the `rules` prop. I might should rename `validation` => `rules` or create an alias

**Comment by dohomi** [comment]
You can use your own `onChange` handler for formatting or you can pass other Material-UI change handler.

**Comment by ajoslin103** [comment]
Thanks for your replies, I appreciate your time!

I've been drilling into the code starting with yours and tracing types and can't figure out how to use validation to call a function.

I have figured out how to use the inputProps to add an onChange, but I can't figure out how to change the value in the form.  Using the InputProps to add an onChange worked to change the value in the form, but then the form value is considered empty (even tho it then shows the formatted value)

**Comment by dohomi** [comment]
Here is a huge collection of examples:
https://github.com/react-hook-form/react-hook-form/tree/master/examples
You can set `validation` prop which is the same as `rules` of react-hook-form. I hope you find an example which suits your usecase

**Comment by ajoslin103** [comment]
thanks for the pointer - I'll suss it out

**Comment by ajoslin103** [comment]
working!!
