### ISSUE TITLE
Build fails after update to 5.10.2

### ISSUE THREAD

**Issue by marcoreni** [dohomi/react-hook-form-mui#104]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

After updating to 5.10.2 build fails unless we install `date-fns`. We're using DatePickerElement but we're using `Dayjs`.

### Expected behavior 🤔

Dayjs should not be required

**Comment by dohomi** [comment]
Fixed with v5.11.0
