### ISSUE TITLE
Add example in StoryBook to set custom validations to sliders.

### ISSUE THREAD

**Issue by mamaniDaniel** [dohomi/react-hook-form-mui#105]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I was using this library and it was very useful. I don't understand how I could add custom validations to the slider.

It would be good to add an example of how validations can be added even taking values ​​from other parts of the form.

I can add the examples that you share to me in a pull request for the story book.

### Examples 🌈

```
<FormContainer
  defaultValues={{}}
  onSuccess={function noRefCheck(){}}
>
  <SliderElement name="slider" />
  <br />
  <SubmitButton />
</FormContainer>
```

**Comment by dohomi** [comment]
Please have a look at https://react-hook-form-material-ui.vercel.app/?path=/story/slider-element--required

Now you can pass in `rules` or `required` prop to SliderElement from version 5.11.0
