### ISSUE TITLE
PasswordRepeatElement dosen't allow to change error message

### ISSUE THREAD

**Issue by AdamZajler** [dohomi/react-hook-form-mui#107]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If you try to pass in `PasswordRepeatElement`:
```
validation={{
              required: 'To pole jest wymagane' // <= Polish Language
            }}
```
Then input is still displaying `This field is required`

### Expected behavior 🤔

String from required should be visible on front 

### Steps to reproduce 🕹

Everything as in Current behavior 😯

**Comment by AdamZajler** [comment]
I repair it; the problem is if you have unified function for messages in validation field that returns `TextFieldElementProps['validation']` and your component for password element look smth like that: 
```
<PasswordElement required name={'register_password'} label={'Hasło'} sx={{ gridColumn: '1/3' }} />
```

You should always add ` type={'password'}`! Event if rendered input have one; because if your function for validation messages have if statements, then if you don't set type attribute the `props.type === 'password' will be undefined :)

I suggest that `type` should be required ;)

**Comment by AdamZajler** [comment]
Update: setting 
```
validation={{
              required: 'pole wymagane'
            }}
```

for `PasswordRepeatElement` dosen't show effect on front

**Comment by AdamZajler** [comment]
Update: for CheckboxButtonGroup there is no way to set `validation` prop

**Comment by dohomi** [comment]
> I repair it; the problem is if you have unified function for messages in validation field that returns `TextFieldElementProps['validation']` and your component for password element look smth like that:
> 
> ```
> <PasswordElement required name={'register_password'} label={'Hasło'} sx={{ gridColumn: '1/3' }} />
> ```
> 
> You should always add ` type={'password'}`! Event if rendered input have one; because if your function for validation messages have if statements, then if you don't set type attribute the `props.type === 'password' will be undefined :)
> 
> I suggest that `type` should be required ;)

the type is always provided but depends if you are showing the visibility of the PasswordElement

**Comment by dohomi** [comment]
> Update: setting
> 
> ```
> validation={{
>               required: 'pole wymagane'
>             }}
> ```
> 
> for `PasswordRepeatElement` dosen't show effect on front

The PasswordElement is using internally the TextFieldElement so you can provide the same properties as described in the Storybook

**Comment by dohomi** [comment]
> Update: for `CheckboxButtonGroup` there is no way to set `validation` prop

rules has been add to the properties of CheckboxbuttonGroup
