### ISSUE TITLE
Need an option to treat whitespaces as empty value for "required" validation

### ISSUE THREAD

**Issue by enthusiva** [dohomi/react-hook-form-mui#115]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

For example, In a text field with "required" validation, If I enter only white space characters, the required validation is not complaining about it. We could do this check by adding additional code during form submit or using custom validation. IMHO, It is a chore and not everyone remembers to perform this check for required fields in their forms.

It will be awesome if this library can provide an option to turn this check on/off at the form level or field level as needed. The expected behavior would be when a required field is entered with a value, it should trim the white spaces and check for a non-empty value during the onBlur/onChange event and display the required error message.

**Comment by dohomi** [comment]
I am not sure if that is something every user would like on each of the TextField elements. I accept a non-breaking PR for this feature.

**Comment by shkreios** [comment]
@enthusiva Your best option is probably to add a custom validation rule via a regex or a function to check for whitespace.

**Comment by dohomi** [comment]
Thanks @shkreios thats the best answer to do this without any overhead on the project scope.
