### ISSUE TITLE
Allow StoryBook composition

### ISSUE THREAD

**Issue by pongells** [dohomi/react-hook-form-mui#116]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Would be cool if you allowed StoryBook composition, so that we can add your storybook examples to our own storybook documentation.

See: https://storybook.js.org/docs/react/sharing/storybook-composition and https://storybook.js.org/docs/react/sharing/package-composition

I did try with: 

```
refs: {
    'react-hook-form-mui': {
      title: "React Hook Form MUI",
      url: "https://react-hook-form-material-ui.vercel.app",
      expanded: false
    }
  }
```

but it does not seem to work..

**Comment by dohomi** [comment]
@pongells any PR is welcome to include that

**Comment by pongells** [comment]
Thanks @dohomi, I can add the URL to storybook on the package.json.. but what worries me is that even adding it manually it is not working.. so maybe the Vercel hosting does not support that kind of integration? I have no clue :) 

https://www.chromatic.com/compare/vercel seems a bit vague about it..
