### ISSUE TITLE
Set custom icon for PasswordElement

### ISSUE THREAD

**Issue by ogflow** [dohomi/react-hook-form-mui#122]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

It would be great to be able to set custom icon, instead of default Visibility and VisibilityOff.

### Examples 🌈

<img width="465" alt="Screenshot 2023-02-03 at 10 36 28" src="https://user-images.githubusercontent.com/43810977/216551686-63f743d0-e69f-4301-97c0-32ff6c69dd47.png">

**Comment by shkreios** [comment]
Created a [pr](https://github.com/dohomi/react-hook-form-mui/pull/123) which adds `renderIcon` render prop.

# Usage

```tsx
<PasswordElement
   name="password"
   label="Password"
   control={control}
   renderIcon={(visable) => (password ? <Visibility /> : <VisibilityOff />)
/>

```
