### ISSUE TITLE
Missing `inputFormat` prop in DatePickerElement component

### ISSUE THREAD

**Issue by kytosai** [dohomi/react-hook-form-mui#127]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

In MUI's DatePicker component document I see `inputFormat` prop but when I use it with DatePickerElement compopnent it gives me a typescript error even though it still works

### Expected behavior 🤔

Update new interface of DatePicker for DatePickerElement, prevent typescript throw type error

<img width="930" alt="image" src="https://user-images.githubusercontent.com/1908652/219910570-d74079b3-7f2c-41fd-a73f-f8d09c3322f3.png">

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

**Comment by dohomi** [comment]
fixed in 5.15.0
