### ISSUE TITLE
labelPlacement prop for CheckboxElement

### ISSUE THREAD

**Issue by AlexandrKostrov** [dohomi/react-hook-form-mui#129]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Label placement is not configurable for CheckboxElement. Adding labelPlacement = 'top' | 'left' | 'right' | 'bottom' prop would be a good feature for this compoment

**Comment by dohomi** [comment]
resolved in 5.15.0

**Comment by AlexandrKostrov** [comment]
Updated to  5.15.0 but still not working

**Comment by dohomi** [comment]
@AlexandrKostrov http://localhost:6006/?path=/story/checkbox--label-position

**Comment by dohomi** [comment]
```ts
<CheckboxElement
    label="Label"
    labelProps={{
      labelPlacement: 'top'
    }}
    name="basic"
  />
```

**Comment by AlexandrKostrov** [comment]
Working now, thanks!
