### ISSUE TITLE
Unable to disable radio buttons

### ISSUE THREAD

**Issue by daviz1982** [dohomi/react-hook-form-mui#130]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The library includes a "disabled" prop for each type of field (but in autocomplete, although is possible by using `autocompleteProps`) but I'm trying to disable `RadioButtonGroup` and is not working in any way.

In the latest version (5.15.0) `labelProps`was added but I'm testing with no results.

### Expected behavior 🤔

I was expecting that `labelProps: { disabled: true }` was making the fields disabled, but it is not working.

On the other hand if this prop is not supposed to do this job, could be possible to add a `disabled` prop in the component? 

### Steps to reproduce 🕹

I'm trying to recreate the behavior in stackblitz here: https://react-ts-hnfyqs.stackblitz.io, but unfortunately I'm getting a library error also

**Comment by dohomi** [comment]
@daviz1982 totally legit request, added in v5.15.1
https://react-hook-form-material-ui.vercel.app/?path=/story/radiobuttongroup--disabled
