### ISSUE TITLE
sx prop for DatePickerElement

### ISSUE THREAD

**Issue by AlexandrKostrov** [dohomi/react-hook-form-mui#131]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Is it possible to add sx prop for DatePickerElement? As it exists for TextFieldElement, SelectElement, etc.

**Comment by dohomi** [comment]
The sx prop does not exist on DatePicker but within `inputProps`:
```ts
<DatePickerElement inputProps={{sx: {/* your code */}}}/>
```
If thats not sufficient you have to wrap `DatePickerElement` into a `<Box/>` and add your `sx` styles there.
