### ISSUE TITLE
Unable to properly pass ref to the MUI input component

### ISSUE THREAD

**Issue by aleksandartepavcevic** [dohomi/react-hook-form-mui#133]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

After the 5.10.2v (that's the last working version), I'm unable to properly pass ref to the input component via inputRef as per [MUI Docs](https://mui.com/material-ui/api/text-field/).

### Expected behavior 🤔

I'm expecting to get input component back.

**Comment by dohomi** [comment]
@aleksandartepavcevic what is your intention with `ref`? Ref is used to work properly with `react-hook-form` and thats why the ref of <Controller/> is passed to <TextField inputRef="ref"/>.

**Comment by aleksandartepavcevic** [comment]
@dohomi I'm using `react-hook-form-mui` with `react-google-autocomplete` ([Link to the docs](https://github.com/ErrorPro/react-google-autocomplete)), specifically usePlacesWidget hook which returns ref that I need to pass to the TextField component.

**Comment by RubtsovAV** [comment]
Got it.

**Comment by dohomi** [comment]
I honestly think you should wire up your own component with `useController` of `react-hook-form` and combine it with `react-google-autocomplete`. There is no need of using any `react-hook-form-mui` component for your use case

**Comment by aleksandartepavcevic** [comment]
@dohomi I've managed to get it working with your solution with the controller. Thanks!
