### ISSUE TITLE
Prop `textFieldProps.InputLabelProps.shrink` don't work

### ISSUE THREAD

**Issue by kytosai** [dohomi/react-hook-form-mui#134]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When i set `textFieldProps.InputLabelProps.shrink` is true in `AutocompleteElement` but it doesn't work

Demo code
```ts
  <AutocompleteElement
    name={AddNewPlanFormFieldsEnum.PaymentStatus}
    options={paymentStatusOptions}
    matchId
    label={t('payment_status')}
    autocompleteProps={{}}
    textFieldProps={{
      fullWidth: true,
      placeholder: t('select_payment_status'),
      InputLabelProps: {
        required: true,
        shrink: true,
      },
    }}
  />
```

![image](https://user-images.githubusercontent.com/1908652/222441890-f1d82af6-25c1-41fb-9940-de1ac0221bf0.png)

### Expected behavior 🤔

Label of TextField input must be `shrink` mode

![image](https://user-images.githubusercontent.com/1908652/222441986-ff5e4ad7-cc5a-4f5f-a7d1-862482c2789d.png)

**Comment by dohomi** [comment]
any PR is appreciated

**Comment by dohomi** [comment]
try with newest release - it should work now
