### ISSUE TITLE
If null passed as a value into controled SelectElement, application fails with Uncaught TypeError: Cannot read properties of null (reading 'id')

### ISSUE THREAD

**Issue by AlexandrKostrov** [dohomi/react-hook-form-mui#137]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

In https://github.com/dohomi/react-hook-form-mui/blob/master/packages/rhf-mui/src/SelectElement.tsx on 62 string there is a condition  if (typeof value === 'object') and I think this is the reason of the failure, because if value will be null, condition 
typeof null === 'object' will be true.

### Expected behavior 🤔

PAssed null as value to controlled SelectElement doesn't cause a failure

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

**Comment by dohomi** [comment]
@AlexandrKostrov you are not supposed to add any value into the `SelectElement`. Because `react-hook-form` is been used you would use the the FormProvider or FormContainer to preset any values. Do you have any code example?

**Comment by dohomi** [comment]
fixed in v6
