### ISSUE TITLE
Upgrade "@mui/x-date-pickers" to version 6.0.1

### ISSUE THREAD

**Issue by agathe-lighthouse** [dohomi/react-hook-form-mui#139]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

`@mui/x-date-pickers` version needs to be updated to `6.0.1`. Otherwise, using the latest version of `react-hook-form-mui` and the latest version of `@mui/x-date-pickers` creates a  conflicting peer dependency:
`Could not resolve dependency:`
`peerOptional @mui/x-date-pickers@">=5.0.0-alpha.6 <6" from react-hook-form-mui@5.16.`

**Comment by dohomi** [comment]
@agathe-lighthouse peerDependencies are set to <6, so your install should work as expected? I haven't start working on v6 migration yet - that just came out recently.

**Comment by agathe-lighthouse** [comment]
@dohomi In my code, I'm using your package `react-hook-form-mui` that includes `"@mui/x-date-pickers": ">=5.0.0-alpha.6 <6"` as a peerDependency. I'm also using `@mui/x-date-pickers`, which I updated from 5.0.8 to 6.0.1. So I now have a conflicting peer dependency in my code. 
To fix this, you could update your version of `@mui/x-date-pickers` to 6.0.1 :) 
Thanks a lot!!

**Comment by dohomi** [comment]
fixed in v6
