### ISSUE TITLE
Why does the package have peer dependencies of both `date-fns` and `@date-io/date-fns`, and why different versions?

### ISSUE THREAD

**Issue by nspaeth** [dohomi/react-hook-form-mui#14]
https://github.com/dohomi/react-hook-form-mui/blob/5b0597f80b72566f86e02605d52ad65011cb706e/package.json#L34
https://github.com/dohomi/react-hook-form-mui/blob/5b0597f80b72566f86e02605d52ad65011cb706e/package.json#L39

Is this needed for some reason?
npm seems to have trouble resolving these dependencies for me because of conflicting versions and I keep having to use `--force`.

**Comment by dohomi** [comment]
@nspaeth yes this is required if you use a datepicker in your forms. if not you can simply ignore it. Instead of using --force you can always use `--legacy-peer-deps` The v4 of Material-UI depends on this 2 date libraries. In the future in v5 this might be handled differently
