### ISSUE TITLE
Chrome autofill does not shrink input labels

### ISSUE THREAD

**Issue by zilijonas** [dohomi/react-hook-form-mui#141]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Chrome autofill does not shrink input labels.

### Expected behavior 🤔

Chrome autofill should automatically shrink input labels.

### Steps to reproduce 🕹

Steps:

1. Open a form with an email and password field
2. Enter any email and password
3. Click submit and let chrome save it
4. Refresh the page
5. Browser autofills the input field, but the label stays in the text hiding the value until any of the fields are focused

**Comment by dohomi** [comment]
is this somehow documented in MUI?

**Comment by morgan5505** [comment]
https://github.com/mui/material-ui/issues/14427
https://bugs.chromium.org/p/chromium/issues/detail?id=1405170

Think this is an issue with material UI

**Comment by dohomi** [comment]
thanks that is very helpful
