### ISSUE TITLE
Overlapping error when using a dash in number field 

### ISSUE THREAD

**Issue by beahoop** [dohomi/react-hook-form-mui#143]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using a Text Field element set to type="number". If you enter a dash (ex. 12-12) the field will give you an error. If you click away then the label will overlap the input value.

### Expected behavior 🤔

Either to not allow a dash or for the field to error but not cover the value.

### Steps to reproduce 🕹

Steps:

1. Step Text Field to type="number"
2. Using a keyboard type "1-1" or anything with a dash
3. Observer field outline turns red
4. Click away from the field
5. Observe the label overlapping input value.

**Comment by dohomi** [comment]
not sure how to fix this edge case.. any PR welcome

**Comment by beahoop** [comment]
Solved by using the onKeyDown prop on TextFieldElement.
And the below function. 
`  const handleKeyDown = (event: React.KeyboardEvent<HTMLDivElement>) => {
        if (event.code === 'Minus') {
            event.preventDefault();
        }
    };`

Thanks!
