### ISSUE TITLE
Issues with matchId when id is 0

### ISSUE THREAD

**Issue by FlorianCassayre** [dohomi/react-hook-form-mui#144]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using the `AutocompleteElement` component with `matchId` set to `true`, the field doesn't behave properly when selecting an option that has an `id` equal to `0`. I see in the code that you are using `||` instead of `??`, this may be the root of the problem.

**Comment by FlorianCassayre** [comment]
Using a patched version of this component where all occurrenced of `.id ||` have been replaced with `.id ??` fixes the issue. I think the other `||` can safely be replaced as well.

**Comment by dohomi** [comment]
fixed in v6

**Comment by FlorianCassayre** [comment]
Excellent I'll upgrade. Thanks for the quick reactivity!
