### ISSUE TITLE
DatePickerElement - Not accepting value as dd/MM/yyyy

### ISSUE THREAD

**Issue by raunaqpurohit** [dohomi/react-hook-form-mui#147]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

to set some default value(in my case I want to edit a form) in a form , it's mandatory to pass value in 'MM/dd/yyyy' format only.
Date Picker element isn't accepting 'dd/MM/yyyy' format dates, even if you explicitely defines format as 'dd/MM/yyyy'. It would only return value in that format but not accept it. 

### Expected behavior 🤔

If I'm passing value in 'dd/MM/yyyy' while editing, it should accept that value as well and proper date should be rendered.

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

**Comment by dohomi** [comment]
I think you need to pass MUI Datepicker `format` prop according to the API. This lib is just wrapping the Datepicker and does not manipulate the passing value
