### ISSUE TITLE
Autofill form values  causing formating issues

### ISSUE THREAD

**Issue by divyam234** [dohomi/react-hook-form-mui#148]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

![Screenshot 2023-04-05 182510](https://user-images.githubusercontent.com/47589864/230088211-0ac216a0-12eb-4a72-9c53-7f23ce077cd8.png)

Autofill is causing  formating issues .Using text field directly from material ui is working fine.

**Comment by dohomi** [comment]
any PR which targets is welcome
