### ISSUE TITLE
Configurable loading spinner in Autocomplete

### ISSUE THREAD

**Issue by byzyk** [dohomi/react-hook-form-mui#149]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Would be great if we could configure the loading spinner in Autocomplete (maybe other places as well?) via the prop, something like `loadingIndicator`

See: https://github.com/dohomi/react-hook-form-mui/blob/master/packages/rhf-mui/src/AutocompleteElement.tsx#L164

Happy to work on the PR myself later this week

It is possible to configure now but having to drill that deep and fix issue with caret animation seems like an overkill for this, implementing custom loading indicator seems like a better solution.

### Examples 🌈

```jsx
<AutocompleteElement loadingIndicator={<MyCustomSpinner />} />
```

**Comment by dohomi** [comment]
Any PR is welcome!
