### ISSUE TITLE
Override InputProps too

### ISSUE THREAD

**Issue by Drezir** [dohomi/react-hook-form-mui#150]
https://github.com/dohomi/react-hook-form-mui/blob/d8cefc9cbef0f19178059039c15e6d19d95d203b/packages/rhf-mui/src/DatePickerElement.tsx#L94

Add also InputProps with big "i"

`                            InputProps={{
                                ...params.InputProps,
                                ...inputProps?.InputProps,
                            }}`

**Comment by dohomi** [comment]
this should be handled with https://github.com/dohomi/react-hook-form-mui/blob/d8cefc9cbef0f19178059039c15e6d19d95d203b/packages/rhf-mui/src/DatePickerElement.tsx#L85 already?

**Comment by Drezir** [comment]
Thing is, that renderInput `params` passes InputProps, which overrides inputProps.InputProps. Specific scenario is that next to endAdornment (which is DatePicker button) I need to also add startAdornment. If I do it now, `inputProps.InputProps` are overriden by InputProps from `params`. I admit that it is a little bit messy since you are playing with DatePicker but I am not able to do it with current Impl

**Comment by dohomi** [comment]
will try to work on this asap

**Comment by dohomi** [comment]
@Drezir after migration to v6 of Datepicker is this issue still present, as the API changed entirely?
