### ISSUE TITLE
CheckboxElement sxProp

### ISSUE THREAD

**Issue by erickjmoreno** [dohomi/react-hook-form-mui#151]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Currently, the SxProp implemented in CheckboxElement is the following

```typescript
<Checkbox
...
 sx={{
   ...rest.sx,
   color: error ? 'error.main' : undefined,
 }}
...
/>
```

So when passing the SxProp with callback, it returns an error, also passing arrays as defined here https://mui.com/system/getting-started/the-sx-prop/#passing-the-sx-prop is not working

Following MUI instructions this would be the correct implementation.

```typescript
<Checkbox
  {...rest}
  color={rest.color || 'primary'}
  sx={[
    {
      color: error ? 'error.main' : undefined,
    },
    ...(Array.isArray(rest.sx) ? rest.sx : [rest.sx]),
  ]}
  value={value}
  checked={!!value}
  onChange={(ev) => {
    onChange(!value);
    if (typeof rest.onChange === 'function') {
      rest.onChange(ev, !value);
    }
  }}
/>;
```

### Expected behavior 🤔

 Passing SxProp with callback or array should properly apply Sx values.

### Steps to reproduce 🕹

Steps:

1. Implement Checkbox
2. Pass callback in Sx function

**Comment by dohomi** [comment]
thanks for your investigation! do you mind open a PR with your fix?

**Comment by dohomi** [comment]
PR is merged thanks for your contribution!
