### ISSUE TITLE
Required Rule don't get updated properly

### ISSUE THREAD

**Issue by TobiasKrahn** [dohomi/react-hook-form-mui#153]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

After setting the required prop of i.a. a TextfieldElement from true to false, the required rule will still be active.

This is due to the [rules of RHF register](https://react-hook-form.com/api/useform/register/#rules).

Currently the rules object will change from 
```
// required
{
  required: "This field is required"
}
```
to 
```
// not required
{}
```
instead it has to be changed to 
```
// not required
{
  required: false
}
```

### Expected behavior 🤔

After setting the required prop to false it should deactivate the required rule properly.

### Steps to reproduce 🕹

https://codesandbox.io/s/young-river-fqo0hs?file=/src/App.tsx

Steps:

1. Uncheck the required checkbox
2. click submit

**Comment by dohomi** [comment]
@TobiasKrahn your codesandbox does not show any `react-hook-form-mui` related components. You see this error on every component or on any specific one?

**Comment by dohomi** [comment]
@TobiasKrahn thanks for your demo. Looking at the code https://github.com/dohomi/react-hook-form-mui/blob/master/packages/rhf-mui/src/TextFieldElement.tsx#L52 seems the default is an empty object which actually works for almost all use cases (I use the lib in many prod environment and never stumbled accrossit).

You can provide also a validation object instead of setting `required`, I tried it like this but it seems to not work either:
https://codesandbox.io/s/silly-cartwright-g9ygq9?file=/src/App.tsx

Strange to be honest, maybe I have to unset the empty `{}` but not sure right now.

**Comment by dohomi** [comment]
Thats what I did here: https://codesandbox.io/s/silly-cartwright-g9ygq9?file=/src/App.tsx:1286-1322
still doesnt seem to be right

**Comment by TobiasKrahn** [comment]
Yes you are right, this would be a valid workaround, but I would suggest to change the addition of the required rule at https://github.com/dohomi/react-hook-form-mui/blob/master/packages/rhf-mui/src/TextFieldElement.tsx#L35 
from 
```ts
if (required && !validation.required) {
  validation.required = 'This field is required'
}
```
to something like this
```ts
validation.required ??= !!required && 'This field is required'
```
to prevent other users to fall into this trap.

**Comment by dohomi** [comment]
@TobiasKrahn the `required` prop shortcut is really only useful if users are happy with only english translation and want to be fast and simple. It mainly just appends the "*" asterix symbol behind the label and has a simple english translation. 

The recommended API is the use of `validation`prop as its just an alias for `rules`. As soon you use i18n you have to use it to translate your error messages.

Feel free to open a PR I can revisit it soon, currently I am bombed with other things at work.
