### ISSUE TITLE
Can't set global error with setError

### ISSUE THREAD

**Issue by ogflow** [dohomi/react-hook-form-mui#155]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I am trying to set global error, as described here
https://react-hook-form.com/api/useform/seterror/

However, following code doesn't change errors object
```
setError('root', { 
  type: 'placeOrder',
  message: 'Failed to place an order'
})
```

### Expected behavior 🤔

I expect this library to inherit behaviour from react-hook-form and work correctly with setting a global error.

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

**Comment by dohomi** [comment]
@ogflow did you use the import statement for setError according to this section: https://github.com/dohomi/react-hook-form-mui#troubleshooting
It might be a context issue so you have to use the import from `react-hook-form-mui`

**Comment by ogflow** [comment]
@dohomi I was actually deconstructing formContext. 

`import { useForm } from 'react-hook-form-mui';

const formContext = useForm();
const {setError} = formContext;`

but now I see that there is an import statement UseFormSetError, so I will try to use it :)

**Comment by dohomi** [comment]
if you have a repro I can have a look, this repro does not do any modification on the core api of react-hook-form
