### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by pjblecha** [dohomi/react-hook-form-mui#156]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

There is no documentation to read on anything other than a basic TextFieldElement.

### Expected behavior 🤔

There will be documentation for all controls in the ecosystem.

### Steps to reproduce 🕹

Steps:

1. Go to demo site.
2. Click on "Show Code."
3. See that the JSON object for any specific Autocomplete is shown, AND NOTHING ELSE.
4. Realize that documentation is what makes acceptance and implementation possible for other developers, so WRITE SOME.

**Comment by iget-esoares** [comment]
Agree! Trying to learn how to use it, but the documentation is poor.

**Comment by dohomi** [comment]
oh shoot, seems that something significant changed with Storybook v7, all props should be part of the Storybook documentation. Thanks pointing that out will re-deploy as soon I found the root for the missing props

**Comment by dohomi** [comment]
Redeployed Storybook and all props should now be back as before. 
https://react-hook-form-material-ui.vercel.app/?path=/docs/autocomplete--docs
