### ISSUE TITLE
Storybook docs are down

### ISSUE THREAD

**Issue by jenshedqvist-mco** [dohomi/react-hook-form-mui#161]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When I go into https://react-hook-form-material-ui.vercel.app/ and try to view the documentation, I get a spinner and error.

It does not matter which component I try to access.

![image](https://github.com/dohomi/react-hook-form-mui/assets/95232493/377bb4e2-5020-462f-9353-0eb16c7b2919)

### Expected behavior 🤔

It loads as usual and shows me the component API :)

### Steps to reproduce 🕹

Steps:

1. Go to https://react-hook-form-material-ui.vercel.app
2. Click any of the links in the sidebar
3. Become sad

**Comment by dohomi** [comment]
thanks for letting me know, I just pushed the new version

**Comment by jenshedqvist-mco** [comment]
> thanks for letting me know, I just pushed the new version

Nice! It works sometimes at least 😅 . But not anywhere

![image](https://github.com/dohomi/react-hook-form-mui/assets/95232493/7dfe0715-1bd3-48fa-970f-5f611d9a8b63)

**Comment by dohomi** [comment]
@jenshedqvist-mco you are right.. just ran through more Stories and upgraded the version. All date related elements should be displayed correctly
