### ISSUE TITLE
How to add custom data attribute to form?

### ISSUE THREAD

**Issue by bsor-dev** [dohomi/react-hook-form-mui#162]
I would like to test in cypress and I need to add a custom data props like `<FormContainer  data-cy={LoginForm}>`. Also className, id, ref doesn't exist from `<FormContainer/>` or `<FormProvider/>`. Is there any way for this

Update: 

Looks like FormProps is the solution only problem I got an error, but it works

`Type '{ 'data-cy': LoginPageId.loginForm; }' is not assignable to type 'FormHTMLAttributes<HTMLFormElement>'.`

**Comment by dohomi** [comment]
Let me know how to improve the typings.
