### ISSUE TITLE
MultiSelectElement should show label than value in the box

### ISSUE THREAD

**Issue by sjdeak** [dohomi/react-hook-form-mui#163]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

![CleanShot 2023-06-06 at 11 31 22](https://github.com/dohomi/react-hook-form-mui/assets/8575264/ca6a1e25-6351-45da-915e-6d892b98bb3f)

When using with Object Array, current [MultiSelectElement](https://react-hook-form-material-ui.vercel.app/?path=/docs/multiselectelement--docs) will show value than label in the box, this can bring confusion to users since value is more developer-facing and not visible in the options.

### Expected behavior 🤔

Suggest changing to display label in box instead, thanks!

**Comment by dohomi** [comment]
If you use object field then you should provide your own `renderValue` similar to this example:
https://github.com/dohomi/react-hook-form-mui/blob/master/apps/storybook/stories/MultiSelectElement.stories.tsx#L160

If you like to change the default any PR is welcome

**Comment by dohomi** [comment]
fixed in 6.2.0

**Comment by sjdeak** [comment]
super thanks!!
