### ISSUE TITLE
MobileDatePicker

### ISSUE THREAD

**Issue by hasanaktas** [dohomi/react-hook-form-mui#164]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

https://mui.com/x/api/date-pickers/mobile-date-picker/

Any chance of providing support for MobileDatePicker?

Thanks.

**Comment by dohomi** [comment]
Isnt MUI rendering the mobile-date-picker on the specified breakpoint?

**Comment by hasanaktas** [comment]
It works as you said, but if I want to completely cancel the keyboard input, the only solution is to use MobileDatePicker.

In the document it states:

> The MobileDatePicker component which works best for touch devices and small screens. It renders the view inside a modal and does not allow editing values directly inside the field.

**Comment by hasanaktas** [comment]
If you want, I can create a pull request for this component.

**Comment by dohomi** [comment]
sure go ahead

**Comment by dohomi** [comment]
released with 6.3.0
