### ISSUE TITLE
Setting textReadOnly to true throws error in DatePickerElement

### ISSUE THREAD

**Issue by jplaut** [dohomi/react-hook-form-mui#167]
I'm getting this error when setting `textReadOnly` to `true` on the DatePickerElement.

<img width="488" alt="Screenshot 2023-06-08 at 4 20 25 PM" src="https://github.com/dohomi/react-hook-form-mui/assets/1207973/284e33b2-7f5c-4701-a080-807d56127ea1">

This is the line where the issue is:

https://github.com/dohomi/react-hook-form-mui/blob/b24b3a0c2c2ba2020e7e15d99b56313d6b58e10a/packages/rhf-mui/src/DatePickerElement.tsx#L101

Should be an easy fix to just change that to `readOnly: true`

**Comment by dohomi** [comment]
fixed in 6.3.0
