### ISSUE TITLE
Use useController hook instead of Controller component 

### ISSUE THREAD

**Issue by valerii15298** [dohomi/react-hook-form-mui#168]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Right now in every component Controller component is used which requires additional nesting of code and makes code readability worse than when using useController hook itself: https://react-hook-form.com/docs/usecontroller.

My proposal is to substitute all usages of Controller component with useController hook.

**Comment by dohomi** [comment]
there is no legitimate reason rewriting all components to `useController` as it neither benefits the API nor improves code stability. 
If you feel like putting your hands on feel free to open PR's as I won't put time and efforts in it unless it solves bugs or known issues.

**Comment by valerii15298** [comment]
Sure, of course. Actually my initial intention was to open a PR :) .
Main point is that it improves code readability and makes it a little bit more concise.

But before opening PR I just wanted to ensure if that is something you would consider and would review pull request for.
Because I didn't want to open PR if maybe you would not even consider moving `Controller` to `useController` for some reasons(even though they are identical in terms of functionality).
So the first step I guess is to agree with author😉

**Comment by dohomi** [comment]
As far as I know the `<Controller>` uses `useController` under the hood. I'm totally fine with either approach, when I started this lib there was actually no `useController`.

Feel free to open PR's I am happy to do the switch if it improves the readability.

**Comment by dohomi** [comment]
closing for now as I don't see any benefit on the user side - will probably migrate if needed over the time.
