### ISSUE TITLE
Match Id Multi  for Autocomplete is not showing proper code

### ISSUE THREAD

**Issue by mxmujeeb** [dohomi/react-hook-form-mui#170]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Match Id Multi  for Autocomplete is not showing proper code as it is not showing how to set the value for the selected items

**Comment by dohomi** [comment]
are you looking for an example? https://react-hook-form-material-ui.vercel.app/?path=/docs/autocomplete--docs#match-id-multi
I quite dont understand what you are looking for.

**Comment by mxmujeeb** [comment]
Dear Dominic,

The match-id option is a boolean only right?
What I wanted was , how can i preselect multiple options when the
autocomplete loads up.

**Comment by dohomi** [comment]
you do this on the react-hook-form with defaultValues: 
https://github.com/dohomi/react-hook-form-mui/blob/master/apps/storybook/stories/AutocompleteElement.stories.tsx#L24

**Comment by mxmujeeb** [comment]
Can we do this with react-hook-form-mui

**Comment by dohomi** [comment]
what is your question?
