### ISSUE TITLE
When importing FormErrorProvider from 'react-hook-form-mui' its undefined 

### ISSUE THREAD

**Issue by skopz356** [dohomi/react-hook-form-mui#173]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When importing FormErrorProvider exactly from 'react-hook-form-mui' the value of it is undefined.

### Expected behavior 🤔

The value of FormErrorProvider  should be function.

**Comment by dohomi** [comment]
Do you have a repo on how you use it?

**Comment by dohomi** [comment]
closing it as there is no further info
