### ISSUE TITLE
Debounce MUI components that rapidly change state

### ISSUE THREAD

**Issue by MauricePasternak** [dohomi/react-hook-form-mui#177]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

RHF does a great job with isolating re-renders to the individual fields. However, other operations like validation are often run on every field change after the initial submission.

If these operations are expensive, performance hits can be observed when components that typically feature rapid changes (i.e. TextField and Slider) are at play. This is offset by debouncing the `onChange` call.

An example comparison has been provided as a CodeSandbox.

### Examples 🌈

https://codesandbox.io/s/mystifying-taussig-gwfptc?file=/src/App.tsx

Please refer to the console logging the validation occurances after the submit button is pressed. Compare the debounced component example versus the current `TextFieldElement` implementation that has been commented out.

**Comment by dohomi** [comment]
Hi @MauricePasternak I never bump into any performance issues using this package. If you are concerned and need 100% performance because you do lot of calculations under the hood you can always use this approach:
https://react-hook-form-material-ui.vercel.app/?path=/docs/formcontainer--docs#strict-typing-form
That does not use FormProvider and thus has no re-renders on form changes.

**Comment by gotenxds** [comment]
If anyone else needs it, here is a version that only updates the form on value commit

```ts
export const SliderSelect = ({ name,...rest}: SliderSelectProps) => {

    return (
      <Controller render={({field: {value, onChange}, fieldState: {error}}) => {
        const [internalValue, setValue] = useState(value);

        useEffect(() => {
          setValue(value);
        }, [value]);

        return <Slider value={internalValue} valueLabelDisplay="auto" {...rest} onChangeCommitted={(e, v) => {
          onChange(v)
        }} onChange={(e, v) => setValue(v)}/>
      }} name={name}/>
    );
};
```

I found that this library is not very optimized and honestly wrapping mui is very easy so it might not be worth using for some cases.
