### ISSUE TITLE
ToggleButtonGroupElement using FormControl does not take the value of fullWidth resulting in external setting fullWidth failure

### ISSUE THREAD

**Issue by faner11** [dohomi/react-hook-form-mui#178]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

ToggleButtonGroupElement set fullWidth does not work properly

### Expected behavior 🤔

fullWidth can take effect

### Steps to reproduce 🕹

Steps:

1. https://github.com/dohomi/react-hook-form-mui/blob/master/packages/rhf-mui/src/ToggleButtonGroupElement.tsx#L76
2.
3.
4.

**Comment by dohomi** [comment]
any reproduction would be helpful.

**Comment by faner11** [comment]
> any reproduction would be helpful.

https://codesandbox.io/s/practical-lucy-6vh22x?file=/src/App.js

**Comment by dohomi** [comment]
fixed in 6.4.0
