### ISSUE TITLE
How to disable Submit on Enter key

### ISSUE THREAD

**Issue by ajoslin103** [dohomi/react-hook-form-mui#18]
I had a problem where the Enter/Return key is causing a submit -- I'm placing a solution here in case others come looking.

This discussion offered some hints on how to prevent such behavior: https://github.com/react-hook-form/react-hook-form/discussions/2549

I had to set the onKey into a div inside the FormContainer

```
  const checkKeyDown = (e) => {
    if (e.key === 'Enter') e.preventDefault()
  }

  return (
    <FormContainer defaultValues={formDefaults} onSuccess={doUpdateData}>
      <div onKeyDown={(e) => checkKeyDown(e)} className={classes.formRoot}>
```

**Comment by ajoslin103** [comment]
Thanks for react-hook-form-mui - it works really well for me

**Comment by Feng94** [comment]
Thanks so much, this was so easy and fixed my issue too!

**Comment by dohomi** [comment]
you might could just use the `FormProps` to add the onKeyDown to the <form> tag. But this hasn't been tested just an idea.
