### ISSUE TITLE
defaultValue of SelectElement don't work

### ISSUE THREAD

**Issue by mingxin-yang** [dohomi/react-hook-form-mui#182]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

```
<SelectElement
                name="weightUnitOfMeasure"
                size="small"
                fullWidth
                required
                defaultValue={"g"}
                options={[
                  {
                    id: "g",
                    label: "g",
                  },
                  {
                    id: "kg",
                    label: "kg",
                  },
                ]}
              />
```

can't show g to default

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

**Comment by oleglukashev** [comment]
same problem. version 6.4.0

**Comment by mingxin-yang** [comment]
you can set defaultValue with name in `FormContainer`，but set in SelectElement don't work

**Comment by oleglukashev** [comment]
thanks a lot!

**Comment by dohomi** [comment]
This library integrates with react-hook-form and default values are set within the hook initialisation (defaultValues of form). Either use FormContainer or `useForm({defaultValues})`

**Comment by kkaplita** [comment]
What when I would like to defaultValue not in form?

I have big object of data and other for customization. And I want to show if value is set in source object, and set data to submit when value is changed (is different than in source object)

**Comment by dohomi** [comment]
> @dohomi What when I would like to defaultValue not in form?
> 
> I have big object of data and other for customization. And I want to show if value is set in source object, and set data to submit when value is changed (is different than in source object)

you have all tools in hand via react-hook-form api. you can run a `useEffect` and `setValue` for manipulating data, it totally depends what your ux is looking like.
