### ISSUE TITLE
[feature request]: Provide possibility to render value

### ISSUE THREAD

**Issue by SimonGolms** [dohomi/react-hook-form-mui#183]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I have a `<SelectElement />` where I would like to display the result for example as a `<Chip />`. Currently I am not aware that this is possible. It would be great if this matches the official MUI documentation: https://mui.com/material-ui/react-select/#chip

### Examples 🌈

```tsx
<SelectElement
  name="demo-chip"
  renderValue={(value) => (
    <Chip key={value} label={value} />
  )}
/>
```

```tsx
<MultiSelectElement
  name="demo-multiple-chip"
  renderValue={(selected) => (
    <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0.5 }}>
      {selected.map((value) => (
        <Chip key={value} label={value} />
      ))}
    </Box>
  )}
/>
```

**Comment by dohomi** [comment]
Check out the source: https://github.com/dohomi/react-hook-form-mui/blob/master/packages/rhf-mui/src/SelectElement.tsx#L72

you can most likely just pass your `renderValue` function to the props like in MUI itself

**Comment by SimonGolms** [comment]
I understand and since it's a [`<Textfield />`](https://mui.com/material-ui/react-text-field/) you have to pass it down with [`SelectProps`](https://mui.com/material-ui/api/text-field/#TextField-prop-SelectProps), e.g.

```ts
<SelectElement
  name="demo-chip"
  SelectProps={{
    renderValue: (value) => <Chip key={value} label={value} />,
  }}
/>
```

However, using Typescript, `value` is `unknown`. Do you have a hint how to pass the types correctly?

**Comment by dohomi** [comment]
just cast the value to whatever type you need it to be, most likely its a `string` I guess
