### ISSUE TITLE
Autocomplete renderValue  

### ISSUE THREAD

**Issue by ch1llysense** [dohomi/react-hook-form-mui#189]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I want to be able to pass any key to Autocomplete.

For example now it works that the renderValue key is only "label".

I want to be able to set it to any or even be able to use options object keys to be able to chain multiple key values.

### Examples 🌈

like so:
```ts
renderValue: (option) => {
   return (
      option.first_name + " " option.last.name
   )
}


```

**Comment by dohomi** [comment]
@ch1llysense you can overwrite `renderValue` `getOptionLabel` or `renderOption`, isn't that sufficient enough?
