### ISSUE TITLE
Allow overriding FormControl props

### ISSUE THREAD

**Issue by Drezir** [dohomi/react-hook-form-mui#190]
https://github.com/dohomi/react-hook-form-mui/blob/d8cefc9cbef0f19178059039c15e6d19d95d203b/packages/rhf-mui/src/RadioButtonGroup.tsx#L84

**Comment by Drezir** [comment]
I have to do:

1. `<FormControl fullWidth error={!!error}>`
2. `sx={{ "& .MuiFormControlLabel-label": { width: "100%" } }} `for option's FormControlLabel

**Comment by dohomi** [comment]
why are you linken an old source? you can pass `formLabelProps` to the component
https://github.com/dohomi/react-hook-form-mui/blob/master/packages/rhf-mui/src/RadioButtonGroup.tsx#L89
