### ISSUE TITLE
Please add unit tests

### ISSUE THREAD

**Issue by chelssw** [dohomi/react-hook-form-mui#192]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

It would be nice to see unit tests written for the components inside of react-hook-form-mui. This library is unnecessarily challenging to test with react-testing-library.

Oddly enough, I have no issue testing standard react hook form components that use material UI components, but testing anything from this library is a heavy burden.

**Comment by dohomi** [comment]
Feel free to open a PR I have currently no time to write tests as I have different assignments.

**Comment by dohomi** [comment]
added chromatic which serves as a solid testrunner. needs to add some play tests for stories but this will get added over the time
