### ISSUE TITLE
Add ability to disable individual options in RadioButtonGroup

### ISSUE THREAD

**Issue by waza-ari** [dohomi/react-hook-form-mui#193]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

It would be nice to have the option to disable individual Radio Buttons with the `RadioButtonGroup`. Right now, it is only possible to disable the entire group at once.

### Examples 🌈

One example:

```ts
<RadioButtonGroup
  label="Label"
  name="My Radio Button Group"
  options={[
    {
      id: 1,
      label: 'ABC',
      disabled: watch('other_field') === "2"
    },
    {
      id: 3,
      label: 'XYZ'
    }
  ]}
/>
```

**Comment by dohomi** [comment]
never had a use for it, but happy to review a PR for this feature

**Comment by acaglarbayatli** [comment]
It would be very nice for the MultiSelectElement too
