### ISSUE TITLE
The location of emptyOptionLabel is optional

### ISSUE THREAD

**Issue by liaokaime** [dohomi/react-hook-form-mui#194]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently, the value of this option is first, but sometimes users want it to be last

**Comment by dohomi** [comment]
any PR is welcome

**Comment by KappaPrajd** [comment]
You can make a workaround using native MUI API. Just include option `{ id: '', label: 'yourEmptyLabel' }` in `options` prop and you can have it at any location ([see sandbox](https://codesandbox.io/p/devbox/react-hook-form-mui-194-w7hzgn?file=%2Fsrc%2FApp.tsx)). Which makes me wonder if the `emptyOptionLabel` prop is really needed if you can make the same thing with native MUI API that is more flexible. What do you think @dohomi?
