### ISSUE TITLE
SwitchElement -  Allow passing props to Switch Component

### ISSUE THREAD

**Issue by sadik-malik** [dohomi/react-hook-form-mui#195]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The Current implementation for SwitchElement does not allow the developers to pass props to Switch Component.

If I want to pass the prop to SwitchElement such as color for customizing the color of switch component  from primary to secondary, I cannot do the same.

```jsx
import {Control, Controller, Path} from 'react-hook-form'
import {FormControlLabel, FormControlLabelProps, Switch} from '@mui/material'
import {FieldValues} from 'react-hook-form/dist/types/fields'

type IProps = Omit<FormControlLabelProps, 'control'>

export type SwitchElementProps<T extends FieldValues> = IProps & {
  name: Path<T>
  control?: Control<T>
}

export default function SwitchElement<TFieldValues extends FieldValues>({
  name,
  control,
  ...other
}: SwitchElementProps<TFieldValues>) {
  return (
    <Controller
      name={name}
      control={control}
      render={({field}) => (
        <FormControlLabel
          control={<Switch {...field} checked={!!field.value} />}
          {...other}
        />
      )}
    />
  )
}

```

In my opinion, there should be some prop like **switchProps** for passing the props to switch component.

**Comment by dohomi** [comment]
fixed in 6.5.2, you can pass now `switchProps` to the component
