### ISSUE TITLE
Make date pickers clearable like autocompletes

### ISSUE THREAD

**Issue by Munhuggas** [dohomi/react-hook-form-mui#196]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The date picker should be clearable out of the box, just like the autocompletes are.

### Examples 🌈

See below how the autocomplete is clearable. The same behaviour would be lovely for the date pickers.

<img width="506" alt="image" src="https://github.com/dohomi/react-hook-form-mui/assets/32365068/a150790c-7767-4175-993b-bffff9d72148">

**Comment by dohomi** [comment]
Any example on the MUI website how to archive this?

**Comment by dohomi** [comment]
The feature is supported via `slotProps`:
```ts
slotProps: {
      actionBar: {
        actions: ['clear']
      }
 }
```
I won't add any features which are part of the API of x-datepicker. You are welcome to add a PR if you need additional functionality

**Comment by Munhuggas** [comment]
Thanks for the reply! The `slotProps` solution is quite different UX wise, though, since it moves the clear function to the popover rather than keeping it in the input field like the autocomplete. I appreciate the suggestion, though.

**Comment by dohomi** [comment]
You can follow this guide, but not sure how much work would be involved https://mui.com/x/react-date-pickers/custom-field/#using-an-autocomplete
