### ISSUE TITLE
DatePickerElement doesn't work with latest x-date-pickers

### ISSUE THREAD

**Issue by kksandr7** [dohomi/react-hook-form-mui#197]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

DateTimePickerElement throws `value.isUTC is not a function` exception with x-date-pickers version 6.13 and AdapterMoment

### Expected behavior 🤔

There should be no exception.

### Steps to reproduce 🕹

Codesandbox demo:

- [No error 6.0.3](https://codesandbox.io/s/x-date-pickers-6-0-3-t47tt3?file=/src/App.js)
- [Error 6.13](https://codesandbox.io/s/x-date-pickers-6-13-qvlkn2?file=/src/App.js)
- [Without react-hook-form-mui](https://codesandbox.io/s/without-react-hook-form-mui-7zzfn3?file=/src/App.js)

**Comment by dohomi** [comment]
You need to provide a default value of `null` instead of `""` and it will work. Seems to be an issue with the moment transform not being able to deal with an empty string value.
https://codesandbox.io/s/x-date-pickers-6-13-forked-rt8sg6
