### ISSUE TITLE
[feature request]: Provide a way to render options of SelectElement

### ISSUE THREAD

**Issue by Karakatiza666** [dohomi/react-hook-form-mui#198]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

For example, I'd like to have a Tooltip with each SelectElement option.
Any suggestion on how to do this using existing API is welcome - I didn't find a way.

### Examples 🌈

```
        <SelectElement
          name='security_protocol'
          value='security_protocol'
           options={[
             {
               id: 'plaintext',
               label: 'plaintext',
               desc: 'Plaintext'
             },
             {
               id: 'ssl',
               label: 'ssl',
               desc: 'SSL'
             }
           ]}
           renderOption={(o) => <MenuItem><Tooltip title={o.desc}><div>{o.label}</div></Tooltip></MenuItem>}
        />
```

**Comment by Karakatiza666** [comment]
@dohomi https://codesandbox.io/p/sandbox/heuristic-solomon-d8jt3l?file=%2Fsrc%2FApp.tsx%3A19%2C28
Passing children to SelectElement isn't supported, so I'm at a loss of what to try in current implementation.

**Comment by dohomi** [comment]
> @dohomi https://codesandbox.io/p/sandbox/heuristic-solomon-d8jt3l?file=%2Fsrc%2FApp.tsx%3A19%2C28 Passing children to SelectElement isn't supported, so I'm at a loss of what to try in current implementation.

if you need to provide children maybe simply write your own implementation for your specific usecase. Without a sandbox I can't see what issues you are currently facing

**Comment by Karakatiza666** [comment]
Please see the sandbox I set up: https://codesandbox.io/p/sandbox/heuristic-solomon-d8jt3l?file=%2Fsrc%2FApp.tsx%3A19%2C28 . I don't need to provide children, I am just suggesting to have a way to customize options of SelectElement.

**Comment by dohomi** [comment]
@Karakatiza666 I see what you are trying to do. As I stated earlier, there is no way to add `<Tooltip />' or any other components to the render of the output of the `<SelectElement/>`. For your specific use case it will be way more easy to run your custom component and use `useController` for the validation of the select element. 
If you can think of an API to feel free to open a PR

**Comment by dohomi** [comment]
As any proposed API would be more complicated than using a custom version and attach `useController` to it I am closing this issue. The scope of this library is to be an easy drop in for general use cases of MUI + RHF
