### ISSUE TITLE
DatePickerElement and TimePickerElement are hiding validation errors reported by MUI components

### ISSUE THREAD

**Issue by gezadev** [dohomi/react-hook-form-mui#199]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The MUI DatePicker and TimePicker components are reporting a range of validation errors defined [here](https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/models/validation.ts). These errors are disregarded and hidden by DatePickerElement and TimePickerElement, resulting in incorrect form submission.

E.g. in case of `invalidDate`:

MUI DatePicker:
![image](https://github.com/dohomi/react-hook-form-mui/assets/64832237/29ae16b6-8325-45b3-93ce-58d661d530d4)
 
DatePickerElement:
![image](https://github.com/dohomi/react-hook-form-mui/assets/64832237/e54c6c22-85bb-474a-b114-a00ca5747ffb)

Same behaviour with all types of invalid date and time value (disabled past or future dates, min and max dates and times, etc.)

### Expected behavior 🤔

Validation errors should be rendered in the same way as in the MUI components.

### Steps to reproduce 🕹

Steps:

1. Pick a date
2. Delete the month part of the date 
3. The component should turn red to show the `invalidDate` error

**Comment by dohomi** [comment]
Do you have any repro and information of what is exactly missing?

**Comment by gezadev** [comment]
The red border is missing, and the fact, that the form can be submitted, although has validation error.

**Comment by gezadev** [comment]
I created a [sandbox](https://codesandbox.io/s/wizardly-chaum-jzw9lj?file=/Demo.tsx) to demonstrate the problem in case of `disablePast` error. Same for all type of validation errors from https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/models/validation.ts

**Comment by sadik-malik** [comment]
I have copied the source code of DatePickerElement and put it a fork of your [sandbox](https://codesandbox.io/s/funny-https-26xv6x?file=/DatePickerElement.tsx) and replaced the following line in DatePickerElement.tsx
```jsx
error: !!error
```

with the following:
```jsx
...(!!error ? { error: true } : {}),
```

This fixed the color issue for DatePickerElement. For validation part, pass setError callback in onError or onChange prop for preventing form submission.

**Comment by dohomi** [comment]
I am currently on vacation, I would appreciate any PR for fixing this issue

**Comment by sadik-malik** [comment]
I have raised the [PR](https://github.com/dohomi/react-hook-form-mui/pull/211) for fixing the validation issue in DatePickerElement by adding the validation rules.

**Comment by dohomi** [comment]
@sadik-malik I saw your PR but started internally to archive it differently. Please check out v6.6.0 which I just published. If the implementation works fine on DatePicker I will extend the validation method to the other picker components as well.

https://react-hook-form-material-ui.vercel.app/?path=/story/datepickerelement--wrong-validated-date

**Comment by sadik-malik** [comment]
@dohomi the current implementation doesn't seem to respect the reValidateMode and mode prop from react-hook-form. As soon as there is an error, it is displayed even when focused is not changed or form is not submitted.

I have created a demo of the same in this [sandbox](https://codesandbox.io/s/objective-hugle-3rl23c) along with its fix.

**Comment by sadik-malik** [comment]
Also, with current implementation the form is getting submitted even when there is an error in DatePickerElement

**Comment by dohomi** [comment]
do you mind creating a PR on the base of the current implementation?

**Comment by sadik-malik** [comment]
I have raised a new [PR](https://github.com/dohomi/react-hook-form-mui/pull/212).

**Comment by dohomi** [comment]
v6.6.1 is available. @sadik-malik thanks for your contribution 👍

**Comment by gezadev** [comment]
The DatePickerElement looks ok now, thanks! Will you extends the fix to the TimePickerElement and DateTimePickerElement also?

**Comment by sadik-malik** [comment]
Raised PR [#213](https://github.com/dohomi/react-hook-form-mui/pull/213). @gezadev, I hope this fixes the validation issues related to DateTimePickerElement and TimePickerElement.

**Comment by gezadev** [comment]
Thank you @sadik-malik!
