### ISSUE TITLE
Accessablity warning: Incorrect use of <label for=FORM_ELEMENT>

### ISSUE THREAD

**Issue by RobLun72** [dohomi/react-hook-form-mui#206]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I have one SelectElement in a gridlist and I get an accessability warning for every instance of the select control: 
Incorrect use of <label for=FORM_ELEMENT>
 
Seems that the for attribute of the label must point to the id of the hidden form input to satisfy the accessability check.
The select html result today setas the id on the visual part of the select...but that does not count as a form element, probably due to data binding issues.

### Expected behavior 🤔

no Incorrect use of <label for=FORM_ELEMENT> warnings when using select element

### Steps to reproduce 🕹

Steps:

1. Use select element in a form
2. Check the issues tab of the chrome dev tools
3.
4.

**Comment by dohomi** [comment]
I honestly don't see any issue on SelectElement as it only uses internally `<TextField/>` from MUI. At least in the local setup of Storybook no warnings has been thrown inside the documentation.

**Comment by RobLun72** [comment]
Hi Dominic,

i'll send you some screenshots of the error or maybe you should say warning
since the component works.

First the page in your storybook

[image: image.png]

then the issues tab
[image: image.png]

and finally issues expanded
[image: image.png]

In my form I get one of those warnings for each select element I use.
If I try to set the id of the select I get 1 blue warning and 1 red warning
for each select element.

When looking in the element viewer you can see that the invisible input
does not have an id, but I think that is the field that counts as the
formfield and the one that the label "for" attribute should point to to
satisfy the accessibility check.

best regards
Robert

Den mån 6 nov. 2023 kl 02:38 skrev Dominic Garms ***@***.***>:

**Comment by dohomi** [comment]
Are we both talking about this page: 

https://react-hook-form-material-ui.vercel.app/?path=/story/selectelement--basic

I'm afraid your pictures are not uploading. I wonder what might be the reason why you see accessability warnings and I'm not..

If you check out the source code you'll see that under the hood there is MUI `<TextField />` element used, do you have the same error as well with the standard `<TextFieldElement/>`?

**Comment by RobLun72** [comment]
yes we are, or any other page with SelectElement.

trying to add pictures another way.

/rob

Den mån 6 nov. 2023 kl 10:19 skrev Dominic Garms ***@***.***>:

**Comment by RobLun72** [comment]
the issue pics are from:
https://react-hook-form-material-ui.vercel.app/?path=/story/autocomplete--basic

but in the:
https://react-hook-form-material-ui.vercel.app/?path=/story/selectelement--basic
there are 3 warnings and the last one points to the select element




Den mån 6 nov. 2023 kl 10:19 skrev Dominic Garms ***@***.***>:

**Comment by dohomi** [comment]
the issue is part of the MUI library. Please research there for a result as this library does not do any magic with the core component of MUI.

<img width="1701" alt="Screenshot 2023-11-06 at 22 13 14" src="https://github.com/dohomi/react-hook-form-mui/assets/489221/3229cf04-7489-47cd-98e8-f4a8d381cb3b">

**Comment by RobLun72** [comment]
Ok, thanks and sorry for the trouble.

/rob

Den mån 6 nov. 2023 15:15Dominic Garms ***@***.***> skrev:
