### ISSUE TITLE
How to set TextField value

### ISSUE THREAD

**Issue by agloolik** [dohomi/react-hook-form-mui#216]
I have a form with a password textfield and a button to generate a password
        <FormContainer onSuccess={onSubmit}>
          <Stack direction={"column"}>
            <TextFieldElement
              name={"name"}
              label={"Name"}
              required
              margin={"dense"}
            />
            <TextFieldElement
              name={"email"}
              type="email"
              label={"Email"}
              required
              variant={"outlined"}
              margin={"dense"}
            />
            <Box
              display="flex"
              alignItems="baseline"
              flexDirection="row"
              gap={1}
            >
              <TextFieldElement
                {...register("password")}
                name={"password"}
                label={"Password"}
                required
                variant={"outlined"}
                margin={"dense"}
                sx={{ height: "56px", flexGrow: 2 }}
              />
              <Button
                onClick={onClickGeneratePassword}
                color={"primary"}
                /* size={"medium"} */
                variant={"contained"}
                margin={"dense"}
                sx={{ height: "56px", flexGrow: 1 }}
              >
                Generate
              </Button>
            </Box>
            <SelectElement
              valueKey="id"
              labelKey="name"
              label="Group"
              name="group"
              options={selectGroups}
              required
              margin={"dense"}
            />
            <br />
            <CheckboxButtonGroup
              label="Special User Access"
              name="access"
              options={[
                {
                  id: "isAdmin",
                  label: "Admin",
                },
                {
                  id: "isModerator",
                  label: "Moderator",
                },
                {
                  id: "isModeratorPlus",
                  label: "Moderator +",
                },
              ]}
              row
              margin={"dense"}
              sx={{ height: "56px" }}
            />
            <br />
            <Button
              type={"submit"}
              color={"primary"}
              size={"medium"}
              variant={"outlined"}
              margin={"dense"}
              sx={{ height: "56px" }}
            >
              Submit
            </Button>
          </Stack>
        </FormContainer>

I imported setValue and call it when I get the generated password like so:
  const { register, setValue } = useForm();

  const onClickGeneratePassword = () => {
    const password = getPassword();
    console.log(password);
    setValue("password", password);
  };

This does not work, could you hint me on the correct way to get this working, many thanks !

**Comment by dohomi** [comment]
you need to use it in a child of the wrapping provider and if you have trouble with the context you have to import the context similar to this: https://github.com/dohomi/react-hook-form-mui#issues-if-context-is-undefined-usewatch

**Comment by agloolik** [comment]
Thank you, I got it working.
