### ISSUE TITLE
How to add custom error handling using react-forms-mui

### ISSUE THREAD

**Issue by Waba-tron** [dohomi/react-hook-form-mui#219]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

How would I add custom error handling or custom input validation using react-hook-forms-mui

For example if a input needed to have a certain number of characters or could should have a special character such as a $.
Another example if i wanted to compare two inputs such as a new password and confirm password, if they didnt match then a error would occur

 Docs also need to be revisited as they are not very insightful and not helpful in the slightest

**Comment by dohomi** [comment]
this library just enables `react-hook-form` so just pass a validate prop it works in the same way you would expect it in the parent library.
`PasswordRepeatElement />` is an exported componen: https://react-hook-form-material-ui.vercel.app/?path=/story/textfieldelement--basic
