### ISSUE TITLE
Storybook demo isn't working

### ISSUE THREAD

**Issue by Here2Huynh** [dohomi/react-hook-form-mui#220]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Demo url is loading into empty page.

<img width="1728" alt="image" src="https://github.com/dohomi/react-hook-form-mui/assets/36244137/79565da9-4ffc-4756-98fb-da73de1cf0cd">

### Expected behavior 🤔

Demo page to load with storybooks of the elements.

### Steps to reproduce 🕹

Steps:

1. go to https://react-hook-form-material-ui.vercel.app

**Comment by dohomi** [comment]
For me the Stories just work fine. You might have a network issue or a browser extension blocks the request?
<img width="1402" alt="Screenshot 2023-11-28 at 09 05 20" src="https://github.com/dohomi/react-hook-form-mui/assets/489221/8f3490f6-5185-47f5-8378-ebfa83cfb982">

**Comment by Here2Huynh** [comment]
it is working for me now, thanks!

**Comment by Here2Huynh** [comment]
I noticed the code samples are weird looking.

<img width="1147" alt="image" src="https://github.com/dohomi/react-hook-form-mui/assets/36244137/1b64d762-d029-47fc-ada9-a707da7c7ae6">

**Comment by dohomi** [comment]
We had this issue before.. that was a compiler issue on Storybook side, I wonder since when the issue re-appeared again. Will try to look into it soon

**Comment by dohomi** [comment]
I created a discussion in Storybook to see what causes this minified output: https://github.com/storybookjs/storybook/discussions/25025

**Comment by dohomi** [comment]
Fixed with latest release

**Comment by rpateld** [comment]
This [URL](https://react-hook-form-material-ui.vercel.app/) was functioning correctly until yesterday, but I've noticed that it has stopped working today.
![image](https://github.com/dohomi/react-hook-form-mui/assets/56134077/3fb90a27-4d7d-43b2-87ca-ba599da4af37)

**Comment by sadik-malik** [comment]
@rpateld [https://react-hook-form-material-ui.vercel.app/](https://react-hook-form-material-ui.vercel.app/) is working fine for me.

**Comment by rpateld** [comment]
It says : 
![image](https://github.com/dohomi/react-hook-form-mui/assets/56134077/30d0fe3a-5041-499e-a9e8-ceff08887295)

**Comment by dohomi** [comment]
@rpateld seems to be an issue with your internet provider or any browser extension, the website works fine for me too
