### ISSUE TITLE
Next Js attribute removal doesn't work on inputProps

### ISSUE THREAD

**Issue by AdamZajler** [dohomi/react-hook-form-mui#221]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

For ex. we have component like this: 
```
`<TextFieldElement 
data-cy="test1"
inputProps={{ "data-cy="test2" }}
/>`
```
. And also we have set compiler options in `next.config.js` to:
```
  compiler: {
    reactRemoveProperties: { properties: ['^data-cy'] },
  }
```

After build, attributes will be removed from wrappers of `<input/>` element, but not from a `<input/>` itself :o

This issue dosent exists on other components like vanilla input tag, only on TextFieldElement etc.

### Expected behavior 🤔

Attributes will be removed everywhere. 

### Steps to reproduce 🕹

Steps:

1. Create component like
`<TextFieldElement 
data-cy="test1"
inputProps={{ "data-cy="test2" }}
/>`
2. Set nextjs config to 
```
  compiler: {
    reactRemoveProperties: { properties: ['^data-cy'] },
  }
```
3. Build your application
4. input tag of `TextFieldElement` shouldn't have `data-cy` attribute, but it has.

**Comment by dohomi** [comment]
closing it here as the fix will be within MUI package
