### ISSUE TITLE
Disabled props not working on DatePickerElement And DateTimePickerElement

### ISSUE THREAD

**Issue by NicholasMata** [dohomi/react-hook-form-mui#224]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using the `disabled` prop on `DatePickerElement` and `DateTimePickerElement` the actually input on the field is not disabled.

The reason for this is the `field` properties from `useController` are spread on the MUI components like so.
```tsx
  <DatePicker
      {...rest}
      {...field}
```

`field` has a `disabled` ([more info here](https://react-hook-form.com/docs/usecontroller)). Since it goes after the `rest` which is the props we actually give the component the `disabled` that we give the components gets overridden.

### Expected behavior 🤔

When using the `disabled` prop on `DatePickerElement` and `DateTimePickerElement` the input as well as the input adornment should be disabled. It should look like the it does in MUI ([example here](https://mui.com/x/react-date-pickers/date-picker/#form-props))

### Steps to reproduce 🕹

Modify any storybook for `DatePickerElement` or `DateTimePickerElement` to include a `disabled: true` in args. And you will see the input is not disabled.

**Comment by NicholasMata** [comment]
## Possible Solutions

1. Since it seems the goal of this library is to be a out of the box bridge between  [`react-hook-form`](https://github.com/react-hook-form/react-hook-form) and [`Material-UI`](https://github.com/mui/material-ui). It would make sense of all components to pass the `disabled` prop to `useController` and / or `<Controller>`. This would make the library work more like [`react-hook-form`](https://github.com/react-hook-form/react-hook-form) as the `disabled` prop is important so that the submission data does not contain the field ([more info](https://react-hook-form.com/docs/usecontroller)). **NOTE: This is a major change (as would be changed for all components not just `DatePickerElement` and `DateTimePickerElement`)**

2. As solution 1 is quite a big change. Another solution is to change `DatePickerElement` and `DateTimePickerElement` to work as the rest of the components do. Which would be simple to do as the only difference between these components and the rest are that the `field` object (which contains disabled property) is spread onto the components.

# Work Around
You can disable the component today like so. (Note: this removed the calendar button) so does not achieve the same result as a [true MUI disabled](https://mui.com/x/react-date-pickers/date-picker/#form-props). 
```tsx
<DatePickerElement
  inputProps={{disabled: true}}
  disableOpenPicker={true}
  />
```

*NOTE: I would be happy to make a PR for whatever solution you prefer.*

**Comment by dohomi** [comment]
since when does the field props contain disabled? That must have been added recently or at least I never came across

**Comment by dohomi** [comment]
ahhh... ok.. this seemed to be added some time ago. Not sure that would be some refactoring required for the component stack.. not a big thing though. Feel free to provide a PR I am happy to have a look

**Comment by NicholasMata** [comment]
Awesome will make a PR for the first solution, thanks for the quick response.

**Comment by dohomi** [comment]
@NicholasMata v6.8.0 is out, thanks for your contribution
