### ISSUE TITLE
fullWidth dosenot exported for AutocompleteElement

### ISSUE THREAD

**Issue by Debnathweb** [dohomi/react-hook-form-mui#226]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Type '{ fullWidth: true; name: "ppu"; label: string; control: Control<IFormInputs, any>; options: { id: string; label: string; }[]; }' is not assignable to type 'IntrinsicAttributes & AutocompleteElementProps<IFormInputs, "ppu", any, boolean | undefined, boolean | undefined, boolean | undefined> & RefAttributes<...>'.
  Property 'fullWidth' does not exist on type 'IntrinsicAttributes & AutocompleteElementProps<IFormInputs, "ppu", any, boolean | undefined, boolean | undefined, boolean | undefined> & RefAttributes<...>'.ts(2322)

### Expected behavior 🤔

able to use fullWidth

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

**Comment by dohomi** [comment]
any reproduction?

**Comment by Debnathweb** [comment]
reproduction [on sandbox](https://codesandbox.io/p/devbox/hd3n2n?file=%2Fsrc%2FForm.tsx%3A72%2C8&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqwc662l0006356kf0zdmk7f%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqwc662l0002356kkhp8hvf0%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqwc662l0003356kuco21yoj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqwc662l0005356knt0myq64%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B58.87941534713764%252C41.12058465286236%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqwc662l0002356kkhp8hvf0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqwc662l0001356k5c5dqpyt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpublic%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqwcliq40002356k2qqvm4id%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A72%252C%2522startColumn%2522%253A8%252C%2522endLineNumber%2522%253A72%252C%2522endColumn%2522%253A8%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FForm.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqwc662l0002356kkhp8hvf0%2522%252C%2522activeTabId%2522%253A%2522clqwcliq40002356k2qqvm4id%2522%257D%252C%2522clqwc662l0005356knt0myq64%2522%253A%257B%2522id%2522%253A%2522clqwc662l0005356knt0myq64%2522%252C%2522activeTabId%2522%253A%2522clqwcv0w0005f356kpd3j88oq%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clqwcv0w0005f356kpd3j88oq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clqwc662l0003356kuco21yoj%2522%253A%257B%2522id%2522%253A%2522clqwc662l0003356kuco21yoj%2522%252C%2522activeTabId%2522%253A%2522clqwcv0pi003t356kbxgyv8uk%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clqwcv0pi003t356kbxgyv8uk%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A24.485294117647058%257D)

**Comment by Debnathweb** [comment]
I try to solve it like this and it is working, is it safe to do
``
`import {
  Control,
  FieldError,
  FieldPath,
  FieldValues,
  useController,
  UseControllerProps,
} from 'react-hook-form';
import {
  Autocomplete,
  AutocompleteProps,
  Checkbox,
  TextField,
  TextFieldProps,
  useForkRef,
} from '@mui/material';
import CircularProgress from '@mui/material/CircularProgress';
import { useFormError } from 'react-hook-form-mui';
import { forwardRef, ReactNode, Ref, RefAttributes } from 'react';

type AutoDefault = {
  id: string | number; // must keep id in case of keepObject
  label: string;
};

export type AutocompleteElementProps<
  TFieldValues extends FieldValues = FieldValues,
  TName extends FieldPath<TFieldValues> = FieldPath<TFieldValues>,
  Value = AutoDefault | string | any,
  Multiple extends boolean | undefined = boolean | undefined,
  DisableClearable extends boolean | undefined = boolean | undefined,
  FreeSolo extends boolean | undefined = boolean | undefined
> = Omit<
  AutocompleteProps<Value, Multiple, DisableClearable, FreeSolo>,
  'name' | 'options' | 'loading' | 'renderInput'
> & {
  name: TName;
  control?: Control<TFieldValues>;
  options: Value[];
  loading?: boolean;
  multiple?: Multiple;
  matchId?: boolean;
  loadingIndicator?: ReactNode;
  rules?: UseControllerProps<TFieldValues, TName>['rules'];
  parseError?: (error: FieldError) => ReactNode;
  required?: boolean;
  label?: TextFieldProps['label'];
  showCheckbox?: boolean;

  textFieldProps?: Omit<TextFieldProps, 'name' | 'required' | 'label'>;
};

type AutocompleteElementComponent = <
  TFieldValues extends FieldValues = FieldValues,
  TName extends FieldPath<TFieldValues> = FieldPath<TFieldValues>
>(
  props: AutocompleteElementProps<
    TFieldValues,
    TName,
    AutoDefault | string | any,
    boolean | undefined,
    boolean | undefined,
    boolean | undefined
  > &
    RefAttributes<HTMLDivElement>
) => JSX.Element;

const AutocompleteElement = forwardRef(function AutocompleteElement<
  TFieldValues extends FieldValues = FieldValues,
  TName extends FieldPath<TFieldValues> = FieldPath<TFieldValues>
>(
  props: AutocompleteElementProps<
    TFieldValues,
    TName,
    AutoDefault | string | any,
    boolean | undefined,
    boolean | undefined,
    boolean | undefined
  >,
  ref: Ref<HTMLDivElement>
) {
  const {
    textFieldProps,

    name,
    control,
    options,
    loading,
    showCheckbox,
    rules,
    loadingIndicator,
    required,
    multiple,
    matchId,
    label,
    parseError,
    ...rest
  } = props;

  const errorMsgFn = useFormError();
  const customErrorFn = parseError || errorMsgFn;

  const validationRules = {
    ...rules,
    ...(required && {
      required: rules?.required || 'This field is required',
    }),
  };

  const loadingElement = loadingIndicator || (
    <CircularProgress color="inherit" size={20} />
  );

  const {
    field,
    fieldState: { error },
  } = useController({
    name,
    control,
    disabled: rest?.disabled,
    rules: validationRules,
  });

  const handleInputRef = useForkRef(field.ref, textFieldProps?.inputRef);

  let currentValue = multiple ? field.value || [] : field.value ?? null;

  if (matchId) {
    currentValue = multiple
      ? (field.value || []).map((i: any) =>
          options.find((j) => (j.id ?? j) === i)
        )
      : options.find((i) => (i.id ?? i) === field.value) ?? null;
  }

  return (
    <Autocomplete
      fullWidth
      value={currentValue}
      loading={loading}
      multiple={multiple}
      options={options}
      disableCloseOnSelect={
        typeof rest.disableCloseOnSelect === 'boolean'
          ? rest.disableCloseOnSelect
          : !!multiple
      }
      isOptionEqualToValue={
        rest.isOptionEqualToValue
          ? rest.isOptionEqualToValue
          : (option, value) => {
              return value ? option.id === (value?.id ?? value) : false;
            }
      }
      getOptionLabel={
        rest?.getOptionLabel
          ? rest.getOptionLabel
          : (option) => {
              return `${option?.label ?? option}`;
            }
      }
      onChange={(event, value, reason, details) => {
        let changedVal = value;
        if (matchId) {
          changedVal = Array.isArray(value)
            ? value.map((i: any) => i?.id ?? i)
            : value?.id ?? value;
        }
        field.onChange(changedVal);
        if (rest?.onChange) {
          rest.onChange(event, value, reason, details);
        }
      }}
      ref={ref}
      renderOption={
        rest?.renderOption ??
        (showCheckbox
          ? (props, option, { selected }) => (
              <li {...props}>
                <Checkbox sx={{ marginRight: 1 }} checked={selected} />
                {rest?.getOptionLabel?.(option) || option.label || option}
              </li>
            )
          : undefined)
      }
      onBlur={(event) => {
        field.onBlur();
        if (typeof rest?.onBlur === 'function') {
          rest.onBlur(event);
        }
      }}
      renderInput={(params) => (
        <TextField
          name={name}
          required={rules?.required ? true : required}
          label={label}
          {...textFieldProps}
          {...params}
          error={!!error}
          InputLabelProps={{
            ...params.InputLabelProps,
            ...textFieldProps?.InputLabelProps,
          }}
          InputProps={{
            ...params.InputProps,
            endAdornment: (
              <>
                {loading ? loadingElement : null}
                {params.InputProps.endAdornment}
              </>
            ),
            ...textFieldProps?.InputProps,
          }}
          inputProps={{
            ...params.inputProps,
            ...textFieldProps?.inputProps,
          }}
          helperText={
            error
              ? typeof customErrorFn === 'function'
                ? customErrorFn(error)
                : error.message
              : textFieldProps?.helperText
          }
          inputRef={handleInputRef}
        />
      )}
      {...rest}
    />
  );
});
AutocompleteElement.displayName = 'AutocompleteElement';

export default AutocompleteElement as AutocompleteElementComponent;
`

**Comment by altwohill** [comment]
You just need to put it in the autocomplete props

```jsx
<AutocompleteElement
  name="brand"
  label="Brand"
  options={brands}
  autocompleteProps={{ freeSolo: true, fullWidth: true, forcePopupIcon: true }}
/>
```
