### ISSUE TITLE
add checked to CheckboxElement or CheckboxButtonGroup

### ISSUE THREAD

**Issue by j09876** [dohomi/react-hook-form-mui#228]
Hi 
I have checked open issues and also the latest version.
How would I add a checked attribute to CheckboxElement or CheckboxButtonGroup?
I have tried to add the attribute to the element and also to use the defaultProps of the mui theme.
Thank you

**Comment by sadik-malik** [comment]
Checked prop is controlled by the react-hook-form in CheckboxElement and CheckboxButtonGroup. Use the values or defaultValues prop in react-hook-form to update checked prop to true or false.

https://stackblitz.com/edit/github-hxddty-gjzjx5?file=src%2FApp.tsx
