### ISSUE TITLE
Disabled elements set form values to undefined

### ISSUE THREAD

**Issue by Munhuggas** [dohomi/react-hook-form-mui#233]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

1. Initialize form values with `useForm` hook.
2. Set an element in the rendered form to `disabled`.
3. The corresponding `form` value is set to `undefined` after first render

### Expected behavior 🤔

I would expect a disabled element to not update the values of the `form`.

### Steps to reproduce 🕹

Ta a look at the console output in the example: https://codesandbox.io/p/sandbox/eloquent-dubinsky-vmqgmr

Note that without react-hook-form-mui this does not seem to happen: https://codesandbox.io/p/sandbox/blissful-shadow-6ftpjd

**Comment by barandurakk** [comment]
It is actually an expected behaviour according to react hook form documentation.
"disabled inputs will appear as undefined values in form values. If you want to prevent users from updating an input and wish to retain the form value, you can use readOnly or disable the entire <fieldset />."

https://react-hook-form.com/docs/useform/handlesubmit

**Comment by Munhuggas** [comment]
I was afraid that would be the answer. Looking at my provided example it doesn't seem to work that way in the latest `react-hook-form` version though. Curiously the linked example from their own documentation uses a beta and alpha version of their libraries.

Seems like we have to rework our entire codebase then and add some custom styling since MUI sadly hasn't cared about styling `readOnly` elements in any particular way.

Perhaps I'll pop a question to `react-hook-form` to see if this is really the intended behaviour since it is not obvious to me that would be the case. From the HTML spec we can see that the form data on submit should indeed not pass any disabled input values. To remedy that you could for example use javascript to save the values for any disabled field. This is exactly what I have used the `defaultValues` of `useForm` to achieve.

Thanks for taking the time to answer!

**Comment by Munhuggas** [comment]
Works as intended.
