### ISSUE TITLE
regex pattern not working

### ISSUE THREAD

**Issue by santhoshkarthi002** [dohomi/react-hook-form-mui#236]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

      <TextFieldElement
            required
            margin="dense"
            name="Interval"
            fullWidth
            label="Duration"
            type="number"
            inputProps={{
              min: 1,
            }}
            validation={{
              pattern: {
                value: /^(0|[1-9]\d*)$/,
                message: 'Duration should have minimum of 1',
              },
            }}
          />

how can i put regex pattern to textfield element for validation

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

**Comment by sadik-malik** [comment]
@santhoshkarthi002: The validation object is being passed to react-hook-form, but it is not triggering the error. This behavior persists even when using native HTML input.

Try using validate instead of pattern in validation prop.

```jsx
validation={{
    validate: (value) => {
      if (!/^(0|[1-9]\d*)$/.test(value)) {
        return 'Duration should have minimum of 1';
      }
    },
  }}
```

**Comment by santhoshkarthi002** [comment]
it,s working, Thank you.

**Comment by waza-ari** [comment]
Just for anyone finding this, with v7 the solution above is no longer valid. Check the v7 beta announcement (#252 ) for details. Essentially it must now be `rules`:

```ts
<TextFieldElement
  ...
  rules={{
    required: true,
    validate: (value) => {
      if (!/^$|^\d+[.,]?\d{0,2}$/g.test(value)) {
        return 'Please enter a valid number..';
      }
    }
  }}
/>
```
