### ISSUE TITLE
`required` prop in ToggleButtonGroupElement is not working

### ISSUE THREAD

**Issue by aq1018** [dohomi/react-hook-form-mui#239]
I think [this line](https://github.com/dohomi/react-hook-form-mui/blob/95506671eb70fe917bc5df3176e18f5281596ae4/packages/rhf-mui/src/ToggleButtonGroupElement.tsx#L68) should be:

```
required: 'This field is required',
```

Instead, `validation` was used as the key.

**Comment by dohomi** [comment]
any PR is welcome, I haven't used that option yet

**Comment by KappaPrajd** [comment]
Can be closed I assume
