### ISSUE TITLE
min/max for TextFieldElement w/ type="number"

### ISSUE THREAD

**Issue by sKopheK** [dohomi/react-hook-form-mui#240]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

i'm missing native min/max props for numeric inputs

**Comment by sadik-malik** [comment]
@sKopheK min and max validation props are already supported in [react-hook-form](https://www.react-hook-form.com/advanced-usage/#TestingForm)

```jsx
 <TextFieldElement
      name="min-max"
      label="Min Max"
      type="number"
      validation={{
        min: {
          value: 1,
          message: 'Must be equal to or more than 1',
        },
        max: {
          value: 10,
          message: 'Must be less than or equal to 10',
        },
      }}
    />
```

**Comment by sKopheK** [comment]
we're talking two different things: validation and allowed input - see https://www.w3schools.com/Html/tryit.asp?filename=tryhtml5_input_max_min for native min/max attributes restricting input

**Comment by dohomi** [comment]
the `inputProps` and `InputProps` where bugging me since day one of MUI :-) I hope they find better namings for this in the v6 release
