### ISSUE TITLE
@mui/x-date-pickers v7

### ISSUE THREAD

**Issue by Xhale1** [dohomi/react-hook-form-mui#244]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Looks like `@mui/x-date-pickers` 7.0.0 [came out today](https://github.com/mui/mui-x/releases/tag/v7.0.0). Would be cool to support it in a future version of this lib.

Lovely work on this project! I appreciate your time and contributions :)

**Comment by dohomi** [comment]
will definitely look into it, most likely i would like to get v7 out of beta in the upcoming time, supporting v7 pickers is a great candidate.

**Comment by bethmaloney** [comment]
@dohomi This is currently blocking us from upgrading to v7 date-pickers. Do you have an idea on when support for v7 will be added or would you be open to a PR that adds v7 support? (against the v7 branch maybe?). Happy to help in any way that I can.

**Comment by dohomi** [comment]
please help to test the new v7 out, `7.0.0-beta.1` released

**Comment by dohomi** [comment]
moved discussion to #252
