### ISSUE TITLE
Autocomplete with multiple and freeSolo option not rendering values

### ISSUE THREAD

**Issue by MarcusKuehn** [dohomi/react-hook-form-mui#245]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

![Bildschirmfoto 2024-03-26 um 17 28 02](https://github.com/dohomi/react-hook-form-mui/assets/159928286/32578b7a-a744-4c0d-9489-272bb4c0929e)

### Expected behavior 🤔

![Bildschirmfoto 2024-03-26 um 17 28 14](https://github.com/dohomi/react-hook-form-mui/assets/159928286/78688992-d576-48a6-b996-7b65b2d62697)

### Steps to reproduce 🕹

```ts
 <AutocompleteElement
               name={"port.stickyMacAllowList"}
               label={"Sticky MAC Allow List"}
               required
               options={[
"00:00:00:00:00:00", "11:00:00:00:00:00"
]}
               multiple
               autocompleteProps={{
                  freeSolo: true,
               }}
            />
```

**Comment by dohomi** [comment]
check https://react-hook-form-material-ui.vercel.app/?path=/story/autocomplete--basic usecases. you have to map your options into [{id: yourId, label: yourLabel}] pairs

**Comment by mrukas** [comment]
Sorry to open this issue again. But freeSolo is not working with this solution. How should you get your input to an object with label and id properties, if freeSolo just returning strings?

The mui docs state the following:

> Be careful when using the free solo mode with non-string options, as it may cause type mismatch.
The value created by typing into the textbox is always a string, regardless of the type of the options.

**Comment by marcellino-ornelas** [comment]
Anyone running into issues with freeSolo and objects as options, you might be running into this issue

https://github.com/mui/material-ui/issues/32042
