### ISSUE TITLE
Enable specifying the required message for "RadioButtonGroup" component

### ISSUE THREAD

**Issue by araujocristian** [dohomi/react-hook-form-mui#249]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

On several component such as TextFieldElement or SelectElement, its possible to define a specific label to warn a user that a field is required with the property "validation" or "rules". For instance :

```
<TextFieldElement
  name="aTextField"
  validation={{ required: 'Champ obligatoire' }}
/>
```
Unfortunately, it not possible with the RadioGroup component.
The following code does not work

```
< RadioButtonGroup
  name="aTextField"
  validation={{ required: 'Champ obligatoire' }} // or rules
/> 
```
It would be great to enable this feature for RadioButtonGroup as well.

As far as I understood, there is no workaround.

### Examples 🌈

![image](https://github.com/dohomi/react-hook-form-mui/assets/19674933/eed59f4f-ba0b-498b-82c1-2e1ab4905d1f)

**Comment by dohomi** [comment]
released in v7 beta
