### ISSUE TITLE
v7 Regression - Introduction of value transformers cause RadioButtonGroup with `type="number"` to return strings

### ISSUE THREAD

**Issue by waza-ari** [dohomi/react-hook-form-mui#253]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

With the latest v7 beta, RadioButtonGroups with `type="number"` return strings again which was originally fixed with e844ada .

I think it might be related to the introduction of custom transformers in bfb7ed7.

### Expected behavior 🤔

When setting `type="number"`, a numeric value should be returned.

### Workaround

Adding this transformer works around the issue, but see comment below:

```ts
                transform={{
                  output: (value) => (value.target.value = parseInt(value.target.value))
                }}
```

**Comment by waza-ari** [comment]
Also, I'm struggeling to understand how transforms are supposed to work in the first place. The typescript signature is:

```ts
(property) transform?: {
    input?: (value: any) => {
        id: MembershipTypeOptions;
        label: string;
    };
    output?: (value: string | {
        id: MembershipTypeOptions;
        label: string;
    }) => any;
}
```

However, when looking for example at https://github.com/dohomi/react-hook-form-mui/blob/a6fe35a66e9fb09e9f59c3f04ac8eaf9c2849fc4/packages/rhf-mui/src/useTransform.ts#L43-45, the `output` function gets an event, not the value.

**Comment by dohomi** [comment]
please check out beta.4 which fixes this regression
