### ISSUE TITLE
Hidden flag does not work

### ISSUE THREAD

**Issue by MarcusKuehn** [dohomi/react-hook-form-mui#255]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Form fields wont hide even when hidden flag is set.

### Expected behavior 🤔

Form fields should be invisible, but value should present in Form data.

### Steps to reproduce 🕹

https://codesandbox.io/p/sandbox/bold-dust-qz3n6w?file=%2Fsrc%2FDemo.tsx%3A14%2C1

**Comment by dohomi** [comment]
If you don't want to show your input field use sx={{display: "none"}}
