### ISSUE TITLE
SwitchElement & CheckboxElement

### ISSUE THREAD

**Issue by kkaplita** [dohomi/react-hook-form-mui#258]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

SwitchElement and CheckboxElement do not send data (undefined, empty) if they are not changed, clicked, and when the path is not straightforward ('some' - works, 'some.next.field' - does not work).

### Expected behavior 🤔

Default value should be send with all paths.

**Comment by dohomi** [comment]
any reproduction? Not sure I understand this task

**Comment by kkaplita** [comment]
Go here: https://react-hook-form-material-ui.vercel.app/?path=/story/switch-element--basic&args=label:Switch+Label

and set for example like this 'switch.some' and click 'Submit'

then... you can see in Actions tab, tkat value for this field is `undefined`

**Comment by dohomi** [comment]
I am not sure, a switch / checkbox is a boolean value, if ckecked the value `true` is sent, if not false. This seems for me expected like this

**Comment by dohomi** [comment]
<img width="456" alt="Screenshot 2024-04-24 at 20 21 04" src="https://github.com/dohomi/react-hook-form-mui/assets/489221/bc2056df-0bfe-40fe-8ed2-d32398e538e3">

**Comment by kkaplita** [comment]
![image](https://github.com/dohomi/react-hook-form-mui/assets/34654152/e4491406-756d-4b9a-a2c1-d3e0eb59bf01)
![image](https://github.com/dohomi/react-hook-form-mui/assets/34654152/1ce449a2-9be7-4df1-9828-04f1fc922970)

**Comment by dohomi** [comment]
the name prop is a singular string - if you start changing the control name to something else you break how the Story is rendered - especially with dot notations. Without a reproduction I won't be able to assist as the switch works as supposed to work

**Comment by dohomi** [comment]
closing for now without reproduction I can't understand the underlying issue.

**Comment by gotenxds** [comment]
The bug is that the switch elements default to undefined as the value so it writes undefined as a default value to the form which is incorrect, this can be fixed by adding a `!!` to line 61 here https://github.com/dohomi/react-hook-form-mui/blob/master/packages/rhf-mui/src/SwitchElement.tsx#L61

For anyone who stumbles on this issue and is looking for a quick fix, you can just use the transform like so:

```tsx
```<SwitchElement label='' name={name} transform={{ input: value => !!value }}/>
```
