### ISSUE TITLE
[Feature Request] Add Switch component support

### ISSUE THREAD

**Issue by TkaczykAdam** [dohomi/react-hook-form-mui#26]
There is no support for [Swtich](https://mui.com/components/switches/) component.

It shouldn't be so hard to implement that. I can try to do it tomorrow (UTC+1).

Btw. Good job, this package is simple and reduces a lot of boilerplate code :+1:

**Comment by dohomi** [comment]
@TkaczykAdam thanks I am looking forward for your PR

**Comment by dohomi** [comment]
available from v3.1
