### ISSUE TITLE
Storybook instance is down 

### ISSUE THREAD

**Issue by kailinj** [dohomi/react-hook-form-mui#264]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Nothing loads when I go to https://react-hook-form-material-ui.vercel.app/

### Expected behavior 🤔

Going to https://react-hook-form-material-ui.vercel.app/ loads the Storybook instance for this repo

### Steps to reproduce 🕹

Steps:

1. Go to https://react-hook-form-material-ui.vercel.app/
2. Storybook instance doesn't load

**Comment by dohomi** [comment]
thanks for the report, I wonder what happened at the last release. I fixed the build and the stories should be up

**Comment by kailinj** [comment]
It's working now — thanks for the quick fix! 🙂
