### ISSUE TITLE
CheckboxElement and CheckboxElementProps seem not fit properly

### ISSUE THREAD

**Issue by larsinho81** [dohomi/react-hook-form-mui#274]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I want to create a thin wrapper for the CheckboxElement, that sets data-testid properties in a unified manner using the name attribite. Unfortunately, the props of type CheckboxElementProps cannot be passed through. There is a TypeScript compile error.

`Type '{ classes?: Partial<CheckboxClasses> | undefined; checkedIcon?: ReactNode; color?: OverridableStringUnion<"error" | "primary" | "secondary" | "info" | "success" | "warning" | "default", CheckboxPropsColorOverrides> | undefined; ... 294 more ...; children?: ReactNode; }' is not assignable to type 'RefAttributes<HTMLDivElement>'.
  Types of property 'ref' are incompatible.
    Type '((instance: HTMLButtonElement | null) => void) | RefObject<HTMLButtonElement> | null | undefined' is not assignable to type 'Ref<HTMLDivElement> | undefined'.
      Type '(instance: HTMLButtonElement | null) => void' is not assignable to type 'Ref<HTMLDivElement> | undefined'.
        Type '(instance: HTMLButtonElement | null) => void' is not assignable to type '(instance: HTMLDivElement | null) => void'.
          Types of parameters 'instance' and 'instance' are incompatible.
            Type 'HTMLDivElement | null' is not assignable to type 'HTMLButtonElement | null'.
              Type 'HTMLDivElement' is missing the following properties from type 'HTMLButtonElement': disabled, form, formAction, formEnctype, and 15 more.ts(2322)`

### Expected behavior 🤔

It should be possible to spread the props property of type CheckboxElementProps to CheckboxElement.

### Steps to reproduce 🕹

Create a component like this:

**rhf-checkbox.tsx**
```
import { FunctionComponent } from 'react';
import { CheckboxElement, CheckboxElementProps } from 'react-hook-form-mui';

const RFHCheckbox: FunctionComponent<CheckboxElementProps> = (props) => {
  return <CheckboxElement {...props} />;
};

export default RFHCheckbox;
```

**Comment by larsinho81** [comment]
Affects version 7.0.0

**Comment by dohomi** [comment]
your code snippet looks incomplete to me, you don't seem to forward proper types. It would be good to see a codepen to actually see what kind of code you are trying to archive

**Comment by larsinho81** [comment]
Sorry, the example was not propely formatted as code and some parts where removed unintentionally. Does it make sense now? Here is an example how I have wrapped the TextFieldElement in the same way, adding default test ids and styling. That is basically what I intend to do with CheckboxElement as well.

**rth-text-field.tsx**
```
import { FunctionComponent } from 'react';
import { TextFieldElement, TextFieldElementProps } from 'react-hook-form-mui';
import { dataTestId, inputDataTestId } from './util/form-element-helper';
import { muiDefaultProps } from './util/mui-default-props';

const RHFTextField: FunctionComponent<TextFieldElementProps> = (props) => {
  const { name, inputProps, ...rest } = props;

  return (
    <TextFieldElement
      name={name}
      {...dataTestId(name)}
      {...muiDefaultProps}
      {...rest}
      inputProps={{
        ...inputDataTestId(name),
        ...inputProps
      }}
    />
  );
};

export default RHFTextField;
```

**form-element-helpers.ts**
```
export const dataTestId = (name: string) => {
  return { 'data-testid': `form-element-${name}` }; // eslint-disable-line
};

export const inputDataTestId = (name: string) => {
  return { 'data-testid': `form-element-${name}-input` }; // eslint-disable-line
};
```

**mui-default-props.ts**
**export interface MuiDefaultProps {
  variant: 'filled' | 'outlined' | 'standard';
  size: 'small' | 'medium';
  fullWidth?: boolean;
}

export const muiDefaultProps: MuiDefaultProps = {
  variant: 'filled',
  size: 'small',
  fullWidth: true
};**

**Comment by dohomi** [comment]
as you can see here: https://github.com/dohomi/react-hook-form-mui/blob/master/packages/rhf-mui/src/TextFieldElement.tsx#L15 you are not properly forwarding the props to the `TextFieldElementProps` so you basically don't get your typings to work. You have to use similar pattern similar to:
```ts
TextFieldElementProps<
  TFieldValues extends FieldValues = FieldValues,
  TName extends FieldPath<TFieldValues> = FieldPath<TFieldValues>,
  TValue = unknown,
>
```

**Comment by larsinho81** [comment]
Hey @dohomi,

thanks for your reply. The TextField works fine, it was only an example. I figured out that the error stated comes from spreading the ref property. I omitted it for now and will try to forward it properly and then it should be fine. Will let you know :)

**Comment by dszymczuk** [comment]
I have the same issue. When I create this component

```javascript
export const CheckboxField = ({ name, label, ...rest }: CheckboxElementProps) => {
    return <CheckboxElement
        label={label}
        name={name}
        {...rest}
    />;
};
```

I've got error on  `CheckboxElement`:

`Type '{ classes?: Partial<CheckboxClasses> | undefined; checkedIcon?: ReactNode; color?: OverridableStringUnion<"error" | "primary" | "secondary" | "info" | "success" | "warning" | "default", CheckboxPropsColorOverrides> | undefined; ... 314 more ...; name: string; }' is not assignable to type 'RefAttributes<HTMLDivElement>'.
  Types of property 'ref' are incompatible.
    Type '((instance: HTMLButtonElement | null) => void | (() => VoidOrUndefinedOnly)) | RefObject<HTMLButtonElement> | null | undefined' is not assignable to type 'LegacyRef<HTMLDivElement> | undefined'.
      Type '(instance: HTMLButtonElement | null) => void | (() => VoidOrUndefinedOnly)' is not assignable to type 'LegacyRef<HTMLDivElement> | undefined'.
        Type '(instance: HTMLButtonElement | null) => void | (() => VoidOrUndefinedOnly)' is not assignable to type '(instance: HTMLDivElement | null) => void | (() => VoidOrUndefinedOnly)'.
          Types of parameters 'instance' and 'instance' are incompatible.
            Type 'HTMLDivElement | null' is not assignable to type 'HTMLButtonElement | null'.
              Type 'HTMLDivElement' is missing the following properties from type 'HTMLButtonElement': disabled, form, formAction, formEnctype, and 15 more.ts(2322)`

As a solution, I created the type:
```typescript
type CheckboxFieldType = Omit<CheckboxElementProps, "ref">
```

And this code works fine
```javascript
export const CheckboxField = ({ name, label, ...rest }: CheckboxFieldType) => {
    return <CheckboxElement
        label={label}
        name={name}
        {...rest}
    />;
};
```

**Comment by dohomi** [comment]
you must do proper type forwarding to satisfy typescript. If you want to roll your own CheckboxField then you have to basically repeat how the CheckboxElement is providing types. Similar to https://github.com/dohomi/react-hook-form-mui/issues/274#issuecomment-2165187052
