### ISSUE TITLE
SelectElement with default preselected option

### ISSUE THREAD

**Issue by FDiskas** [dohomi/react-hook-form-mui#287]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I was unable to preselect the default option by providing `defaultValue` option to a `SelectElement`
If I do render simple MUI component it works 

### Expected behavior 🤔

I should be able to use `defaultValue`

### Steps to reproduce 🕹

Example: https://react-f3w5pk.stackblitz.io

**Comment by dohomi** [comment]
https://github.com/dohomi/react-hook-form-mui/blob/master/apps/storybook/stories/TextFieldElement.stories.tsx#L27 you provide `defaultValues` to React Hook Form once for all fields.
