### ISSUE TITLE
DateRangePicker

### ISSUE THREAD

**Issue by FDiskas** [dohomi/react-hook-form-mui#290]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I would like to use date range picker 

### Examples 🌈

https://mui.com/x/react-date-pickers/custom-field/#use-single-input-fields-on-range-pickers

**Comment by dohomi** [comment]
that is a PRO component so it won't be part of this library which is MIT licenced.
