### ISSUE TITLE
passwordInput There are interaction problems

### ISSUE THREAD

**Issue by leessmin** [dohomi/react-hook-form-mui#291]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

![image](https://github.com/user-attachments/assets/8365bbdd-eb77-452a-91e3-3e0bf378bf09)
When I click on the eye, my cursor runs to the start position, the official mui one I have below doesn't do this.
This is not a problem with my code, because I looked at your example and it also has this problem

### Expected behavior 🤔

The cursor position should not change.

### Steps to reproduce 🕹

Steps:

1.no steps,please look https://react-hook-form-material-ui.vercel.app/?path=/docs/textfieldelement--docs  PasswordElement  and PasswordRepeatElement
2.
3.
4.

**Comment by leessmin** [comment]
OH, my problem, I'm using mui v6, the official v5 version of mui has the same problem!

**Comment by dohomi** [comment]
I will close this for now. v6 is planned but only as soon it reaches stable.
