### ISSUE TITLE
How are you meant to display custom errors?

### ISSUE THREAD

**Issue by nspaeth** [dohomi/react-hook-form-mui#3]
Based on this function it seems that this is either not possible, or not ergonomic: https://github.com/dohomi/react-hook-form-mui/blob/c788fab31a66c982a7befe117da28b6de2a3c19c/src/helpers/getErrorMessages.ts#L3-L11

It seems like the `message` field should be returned by default, not the `type` field. Or, at least, the whole error should be passed to the `parseError` so that a function can be provided to pass the correct thing.

I feel like `parseError` should just be something like `(errors) => getPath(fieldName, errors)` by default, or is should be possible to define a form-wide `parseError` in `FormContainer`.

I could make a pull request if that would help. As it is, `getErrorMessages` seems too opinionated.

**Comment by dohomi** [comment]
@nspaeth thanks for your input. I created parseError to make error messages translatable:
```js
export const parseError = (errorType: string) => {
  if (errorType === 'required') {
    return i18next.t('validations.required')
  }
  if (errorType === 'pattern') {
    return i18next.t('validations.email')
  }
  if (errorType === 'passwordMismatch') {
    return i18next.t('validations.password')
  }
  return i18next.t('validations.default')
}

// inside of a component:
<InputElement parseError={parseError} (...) />

```

**Comment by nspaeth** [comment]
Okay, I can see how this would be useful for that but it would be nice if this were configurable, e.g., by allowing `parseError` to define all of that logic. For example, I might want to do my internationlization in my validator and then use Yup's `setLocale`:

```
const schema = yup.object().shape({
	confirm_password: yup.string()
		.required()
		.oneOf([ yup.ref('password'), null ], i18next.t('validations.passwords_match')),
	...,
}); 
```
If the API were changed so that the logic of `getErrorMessages` was inside of `parseError` it would be more flexible, allowing developers to use any error format they want.

```
const parseError = (name: string, errors: any) => errors[name].message
function MyForm() {
	...
	return <FormContext parseError={parseError} ...>...</FormContext> 
}
```

You could then still achieve your implementation with:
```
export const i18nError = (errorType: string) => {
  if (errorType === 'required') i18next.t('validations.required')
  if (errorType === 'pattern') i18next.t('validations.email')
  if (errorType === 'passwordMismatch') i18next.t('validations.password')
  return i18next.t('validations.default')
}
const parseError = (name: string, errors: any) => {
	const fieldError = getNestedValue(errors, name) || undefined 
 	const errorType: string | undefined = fieldError?.type 
 	if (Array.isArray(fieldError)) console.error('Unexpected field error', fieldError)
    if (!errorType) return 
    return i18nError(errorType)
}
function MyForm() {
 ...
 return <FormContext parseError={parseError} ...>...</FormContext> 
}
```
You could even make the existing behaviour the default so that you won't have to change any of your existing dependant code.

**Comment by dohomi** [comment]
I am happy to check a PR if you have time for it. Currently I am pretty busy but will try to make time for it.

**Comment by dohomi** [comment]
@nspaeth I reworked the entire lib and raised now v1.1.x
`parseError` receives now the `FieldError` which should make everything more customizable. Closing this for now let me know if something is not working as expected.

**Comment by nspaeth** [comment]
Excellent, I'll update and see how it goes.
