### ISSUE TITLE
Show sample documentation for how to use `transform` prop

### ISSUE THREAD

**Issue by Skarvion** [dohomi/react-hook-form-mui#300]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently in the storybook, there's no sample on how to use the `transform` props, particularly for `output`. I have a use case where I have an `<AutocompleteElement>` that contains an array of objects, and I want to return only one of the fields when submitting the form.

I understand this is probably more of a RHF question, but since there are a lot of generics being passed to the elements and the `transform` prop is already available here, I'd like to have a complete sample documented.

The following is a sample code, how to get the `dialCode` in the form submission

```tsx
"use client";

import Button from "@mui/material/Button";
import { AutocompleteElement, FormContainer } from "react-hook-form-mui";

const countriesWithDialCode = [
  { id: "US", label: "United States", dialCode: "+1" },
  { id: "GB", label: "United Kingdom", dialCode: "+44" },
  { id: "CA", label: "Canada", dialCode: "+1" },
  { id: "AU", label: "Australia", dialCode: "+61" },
];

export default function Temp2Page() {
  return (
    <div className="w-1/2">
      {/* Would return the entire object, how to get dialCode? */}
      <FormContainer onSuccess={(data) => console.log(data)}>
        <AutocompleteElement name="dialCode" options={countriesWithDialCode} />
        <Button type="submit">Submit</Button>
      </FormContainer>
    </div>
  );
}
```

**Comment by dohomi** [comment]
Your usecase is covered with the matchId prop:
https://react-hook-form-material-ui.vercel.app/?path=/docs/select-autocomplete--docs#match%20id

**Comment by dohomi** [comment]
can you provide a Codegen or Stackblitz? If you dont use matchId you usually receive the full object of your option you selected, in your case the object like `{id, label, dialCode}`

**Comment by Skarvion** [comment]
You're correct that I can get the full object, which is workable. But by getting the full object, I have to tweak a zod validation scheme to the custom object, which makes the code slightly complex. Moreover, when saving, there will be extra code to maintain when converting a data following zod scheme to get its core part.

I'm basically looking a way at simplifying the code outside of the form since I know I only need the `dialCode`, not the entire object.

I've put it up here: https://stackblitz.com/edit/vitejs-vite-ff8dir?file=src%2FApp.tsx
Please also check the output in the console.

**Comment by dohomi** [comment]
I am not sure if the user would like to see US instead of CA because the dialCode is not unique. I really think you have an edge case here, I am not sure how you'd tweak your zod schema but again, we are talking about persisting your value also in the database, right? If you only persist the dialCode, how should the user know if its US or CA? 

For me it seems your use case can either be handled with a useWatch or you simply convert the object before persisting to the database and pick the right value, but either way, in my opinion you have to use a unique identifier. If you really don't mind the code from @sadik-malik is great way to solve it.

**Comment by Skarvion** [comment]
@sadik-malik That works! Thank you very much.

@dohomi In this particular use case, I only need the dial code and the exact country doesn't matter much for data keeping. I suppose I need to reconsider if I want to use country code as unique identifier now since you're correct that better to pick a more unique selection. Thanks for your input
