### ISSUE TITLE
How to use setAsValue?

### ISSUE THREAD

**Issue by tjx666** [dohomi/react-hook-form-mui#306]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

I want to use setAsValue to trim the user input, but can't find a way to do this.

ref: https://github.com/orgs/react-hook-form/discussions/8903#discussioncomment-10241028

**Comment by sadik-malik** [comment]
@tjx666 `setValueAs` is not supported by react-hook-form-mui components since these components rely primarily on useController. You can achieve the same behavior as setValueAs by using the output function in the transform prop.

**Comment by tjx666** [comment]
thanks reply
