### ISSUE TITLE
Incorrect PasswordElement renderIcon logic is displayed

### ISSUE THREAD

**Issue by tstiemerling** [dohomi/react-hook-form-mui#309]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

By default the renderIcon (eye) is be open, but input is not displayed.

### Expected behavior 🤔

By default the renderIcon (eye) should be closed, since input is not displayed by default. Once you click on the icon then it should display open eye. I dont see a property to control this, so has to be changed in the code.

### Steps to reproduce 🕹

See password demo here: https://react-hook-form-material-ui.vercel.app/?path=/docs/formcontainer--docs

**Comment by dantheother** [comment]
For what it's worth, MUI themselves have it this way in their Input Adornments examples https://mui.com/material-ui/react-text-field/#input-adornments

And, it matches the way MS Edge does their password reveal icon. Which I've always thought as as "backwards", but it's precedent. https://learn.microsoft.com/en-us/microsoft-edge/web-platform/password-reveal

**Comment by tstiemerling** [comment]
Weird, and still totally backwards..

**Comment by tstiemerling** [comment]
Closing as can be fixed in user code
