### ISSUE TITLE
`@mui/x-date-pickers` v 7.17 cause "Attempted import error: 'validateDate' is not exported from '@mui/x-date-pickers/internals'"

### ISSUE THREAD

**Issue by Skarvion** [dohomi/react-hook-form-mui#310]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

In a NextJS project, when using the latest `@mui/x-date-pickers` package v 7.17 and then build, the following warning message is raised

`Attempted import error: 'validateDate' is not exported from '@mui/x-date-pickers/internals'`

Honestly, I don't know what the actual impact when testing it, but the warning message is a bit concerning whereas last week it wasn't there.

See https://github.com/mui/mui-x/pull/14486 that moves the `validateDate` export from `@mui/x-date-pickers/internals` to `@mui/x-date-pickers/validation`

I suppose an easy fix is to use the new import path, but since that PR introduces a new validation hook, I'll leave it up to your discretion how to fix import issue.

For now, to avoid the error, I can use older version of `@mui/x-date-pickers`

### Expected behavior 🤔

-

### Steps to reproduce 🕹

Steps:

1. Create a NextJS project (probably can use vanilla React project, but I haven't test)
2. Install `@mui/x-date-pickers@7.17.0`
3. Add `<DatePickerElement>`
4. Build
5. Warning message in console

**Comment by sadik-malik** [comment]
@dohomi we may be able to support older versions using try catch and dynamic import.

- Load validateDate from new path i.e. import { validateDate }  from '@mui/x-date-pickers/validation'.
- If imports fails then fallback to '@mui/x-date-pickers/internals'.

The other way, if we are not keeping backward compatibility, then we can go with the new import path and change the minimum version for '@mui/x-date-pickers'

**Comment by dohomi** [comment]
Ok thanks for pointing this out.

**Comment by Skarvion** [comment]
> Hi! Any workaround?

`npm install @mui/x-date-pickers@7.16.0`
