### ISSUE TITLE
Add support for HiddenElement

### ISSUE THREAD

**Issue by tstiemerling** [dohomi/react-hook-form-mui#313]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Would be nice to have support for HiddenElement or similar which is basically <input type="hidden" /> with some wrapper code so the value can be defined in the default form data and sent to the onSuccess callback along with other inputs. Right now I have to have some extra useState variables to handle this separately from the form data.

**Comment by sadik-malik** [comment]
@tstiemerling, could you clarify your use case? I'm not entirely sure which `default form data` you're trying to pass to the `onSuccess` callback.

Also, I am not in favor of adding a deprecated component like [MUI Hidden](https://mui.com/material-ui/react-hidden/) to `react-hook-form-mui`.

**Comment by dantheother** [comment]
I believe OP is probably asking about something that helps with `input type=hidden`, rather than CSS hidden, which is what the MUI Hidden was all about.

I've not tried to do this myself using react hook form, nor mui, so I can't speak to what extra functionality a library could offer here.

**Comment by sadik-malik** [comment]
Okay, then the following code can be used to register the field while keeping it hidden in the form.

```jsx
<input {...register("test")} type="hidden"/>
```
