### ISSUE TITLE
startAdornment in PasswordElement

### ISSUE THREAD

**Issue by axelvalles** [dohomi/react-hook-form-mui#317]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using the PasswordElement with a startAdornment, the endAdornment responsible for toggling password visibility is removed, breaking the show/hide functionality.

### Expected behavior 🤔

The endAdornment for toggling password visibility should remain functional even when a startAdornment is provided.

### Steps to reproduce 🕹

Steps:

1. Use the PasswordElement component.
2. Add a startAdornment
3. Observe that the password toggle icon (endAdornment) is no longer visible.

[Code sandbox](https://codesandbox.io/p/sandbox/whmdgr?file=%2Fsrc%2FApp.tsx%3A6%2C31)

**Comment by sadik-malik** [comment]
@axelvalles Thank you for reporting this issue! I have raised a PR #318 to fix it.
