### ISSUE TITLE
Feature: Giving some props to InputAdornment

### ISSUE THREAD

**Issue by TomFreudenberg** [dohomi/react-hook-form-mui#41]
Hi @dohomi 

would it be possible to allow controlling the InputAdornment of PasswordElement(s)

https://github.com/dohomi/react-hook-form-mui/blob/master/src/PasswordElement.tsx#L16

It would be great to control optionally **position** and **color** of the VisibilityIcons

Thanks for your suggestion, I am able to prepare a PR if you like

Cheers
Tom

**Comment by dohomi** [comment]
@TomFreudenberg I am open for any PR 👍

**Comment by dohomi** [comment]
#46 is closing it for now thanks for the contribution
