### ISSUE TITLE
Cannot set 0 in `SelectElement`

### ISSUE THREAD

**Issue by TkaczykAdam** [dohomi/react-hook-form-mui#42]
The problem is here, 0 is a falsy value.The nullish coalescing operator (`??`) here fixed my issue.
https://github.com/dohomi/react-hook-form-mui/blob/46ffb5ca9f8cac21f1890d7f70d2e8678dd070f3/src/SelectElement.tsx#L53

**Comment by dohomi** [comment]
@TkaczykAdam I will deploy a fix for it. Never bumped into this :-)
