### ISSUE TITLE
Run tests in repo

### ISSUE THREAD

**Issue by TimMikeladze** [dohomi/react-hook-form-mui#44]
There is a folder that includes tests but there is no test runner like jest or integration with storybook. I suspect the tests were being ran locally with some ignored folder based on the imports they are using `import { FormContainer, MultiSelectElement } from '../_unused'`.

@dohomi can you provide some additional details around your testing strategy?

**Comment by dohomi** [comment]
@TimMikeladze I use Storybook and wanted to set up `Chromatic` for UI regression tests. I am open for any other suggestions.

**Comment by dohomi** [comment]
Probably Vitest would be a good repo to run test on it. I also thought of moving to Docz for better documentation on the components.

**Comment by dohomi** [comment]
Added chromatic visual test runner
