### ISSUE TITLE
Remove `src` from  `files` in `package.json`

### ISSUE THREAD

**Issue by TimMikeladze** [dohomi/react-hook-form-mui#45]
```
  "files": [
    "dist/**",
    "src"
  ],
```

Including `src` will result in these files being included in npm package. There are currently 20 files added to the npm package (according to https://www.npmjs.com/package/react-hook-form-mui) when in reality there should only be 3. (.js, .mjs, d.ts).

**Comment by dohomi** [comment]
True, will do this with the next patch release

**Comment by dohomi** [comment]
fixed in latest release
