### ISSUE TITLE
Failing github workflow

### ISSUE THREAD

**Issue by TimMikeladze** [dohomi/react-hook-form-mui#47]
Looks like there are two github workflows in this repo:

one of them is passing and this one is failing https://github.com/dohomi/react-hook-form-mui/blob/master/.github/workflows/main.yml

Both of these workflows achieve the same results albeit with slight variations in their commands.

@dohomi What is the reasoning for having two?

**Comment by dohomi** [comment]
I honestly just merged the PR from you, I haven't really observed it in any detail. Could you have a look whats going on with it? Maybe there was some automerge of Github which leads to two separate ones.
