### ISSUE TITLE
 Props disabled does not work on CheckboxElement.

### ISSUE THREAD

**Issue by HubertMezyk** [dohomi/react-hook-form-mui#49]
When I set disabled = {true} `Checkbox` is still active.

**Comment by dohomi** [comment]
@HubertMezyk I never used the disabled checkbox prop. Any PR is welcome

**Comment by HubertMezyk** [comment]
I created a PR with the addition of props `disabled`.

**Comment by dohomi** [comment]
3.5.7 should make this possible
