### ISSUE TITLE
onChange doesn't fire for TextFieldElement

### ISSUE THREAD

**Issue by sonusindhu** [dohomi/react-hook-form-mui#52]
Hi,

I am not able to figure it out how to fire the `onChange` event for `TextFieldElement` component.

Here is the  [Example](https://codesandbox.io/s/tender-rosalind-5wtuls) I have tried.

Could you please let me know if anything special required.

Thanks for the plugin.

**Comment by dohomi** [comment]
The TextFieldElement is using onChange for the internal react-hook-form as you can see here: https://github.com/dohomi/react-hook-form-mui/blob/master/src/TextFieldElement.tsx#L41

If you want to watch changes on the TextFieldElement then just use react-hook-form for this:
```ts
const value = useWatch('nameOfTextfield');
```
