### ISSUE TITLE
Update MUI LAB .86 and X-DATE-PICKERS

### ISSUE THREAD

**Issue by TomFreudenberg** [dohomi/react-hook-form-mui#54]
Dear @dohomi 

thanks again for working on that library and doing the updates !

Would you like to get a PR or would you able to update to the latest MUI Lab 5.0.0-alpha.86

They have moved the date-pickers now into the separated libs: "@mui/x-date-pickers": "5.0.0-alpha.6"

Check out: https://mui.com/blog/lab-date-pickers-to-mui-x/

After just exchanging the imports it worked in our production env.

**Comment by TomFreudenberg** [comment]
Current releases are:

```
    "@mui/icons-material": "5.8.4",
    "@mui/lab": "5.0.0-alpha.86",
    "@mui/material": "5.8.4",
    "@mui/x-date-pickers": "5.0.0-alpha.6",
```

Take care in mind, that NPM will not find the updates for "-alpha", you need to adjust them manual

**Comment by dohomi** [comment]
@TomFreudenberg I've seen the changes of the pickers, there were some typing issues before I definitely will check your PR, hopefully they fixed them. I also consider to provide a convenient form container which includes the DatePickerProvider to reduce imports on the user end

**Comment by dohomi** [comment]
Solved in latest release
