### ISSUE TITLE
add support for resolvers

### ISSUE THREAD

**Issue by keslavi** [dohomi/react-hook-form-mui#57]
very impressive work!    How would you go about adding resolvers, such as yup or joi, into this?   

I've done something similar in another project but didn't publish as it's own npm package, appreciate what you've done in here!

**Comment by dohomi** [comment]
@keslavi this library lets you initiate your form without any magic, just follow react-hook-form guide and choose yup/joi or any other resolver.

Every component either lets you pass in `control` or you can use the `FormProvider`.

**Comment by dohomi** [comment]
@keslavi `v3.8.0` adds the `resolver` prop to the component `FormContainer`

**Comment by khanhzizu** [comment]
> @keslavi `v3.8.0` adds the `resolver` prop to the component `FormContainer`

Can you give me an example?

**Comment by dohomi** [comment]
> > @keslavi `v3.8.0` adds the `resolver` prop to the component `FormContainer`
> 
> Can you give me an example?

you just use a resolver with `useForm` and forward the context to `FormContainer` https://github.com/dohomi/react-hook-form-mui/blob/master/apps/storybook/stories/FormContainer.stories.tsx#L96

**Comment by khanhzizu** [comment]
> `resolver`

thank you very much

**Comment by khanhzizu** [comment]
> > > @keslavi `v3.8.0` adds the `resolver` prop to the component `FormContainer`
> > 
> > 
> > Can you give me an example?
> 
> you just use a resolver with `useForm` and forward the context to `FormContainer` https://github.com/dohomi/react-hook-form-mui/blob/master/apps/storybook/stories/FormContainer.stories.tsx#L96

thank you very much
