### ISSUE TITLE
DateTimePicker support

### ISSUE THREAD

**Issue by CristhianParra** [dohomi/react-hook-form-mui#58]
Add support for DateTimePicker,

I think is possible to use the same implementation of DatePicker :)

**Comment by dohomi** [comment]
@CristhianParra I will try to cover them over the next time. Feel free to open a PR in the mean time, if you need support of it now

**Comment by simonmaquilon** [comment]
Is possible, I solved doing this:

1. Install these libraries:
    "@mui/lab"
    "@mui/x-date-pickers"

2. Replace **this import** in:  _node_modules\@mui\x-date-pickers\DatePicker\DatePicker.d.ts_
// import { ParseableDate } from '@mui/lab/internal/pickers/constants/prop-types';
import { ParseableDate } from '@mui/x-date-pickers/internals/models/parseableDate';

3. Use this code at your requirements:
`<Controller
                name='demo-field'
                control={control}
                render={({ field }) => (
                  <LocalizationProvider dateAdapter={AdapterDayjs}>
                    <DatePicker
                      inputRef={demoRef}
                      onChange={value => onChangeFecha(field, value)}
                      label={demoLabel}
                      value={demoValue}
                      openTo="day"
                      views={['day', 'month', 'year']}
                      inputFormat="DD/MM/YYYY"
                      disabled={data?.completed || data?.aborted}
                      maxDate={djs()}
                      renderInput={params => (
                        <TextField
                          fullWidth
                          margin={'dense'}
                          autoComplete={'off'}
                          size="small"
                          required
                          {...params}
                          helperText={
                            !demoRef.current?.value && submitted.current
                              ? constants.messages.required
                              : null
                          }
                          error={!demoRef.current?.value && submitted.current}
                        />
                      )}
                    />
                  </LocalizationProvider>
                )}
              />`
