### ISSUE TITLE
List of improvments

### ISSUE THREAD

**Issue by ChromeGG** [dohomi/react-hook-form-mui#59]
Hello

I'm currently waiting for my new MacBook, so I don't want to start any big project. I could help develop this open-source project :smile: 

So we can start with simple things to the more advance.

1. Move the changelog to a separate file.
2. Add some badges
![image](https://user-images.githubusercontent.com/39050595/175806165-b69ca9d9-ac7e-4021-8380-8340d97570db.png)
3. Create a logo (logo RHF + logo MUI)
4. Add eslint + prettier
5. Add autocomplete support
6. Better issue templates (like RHF)
![image](https://user-images.githubusercontent.com/39050595/175806345-e8c050e8-69bd-4ac0-bd66-47e7d0361cd5.png)
7. Stackblitz examples

Ofc, I will create separate PRs.

**Comment by dohomi** [comment]
@ChromeGG great I agree to all of your proposals.

**Comment by dohomi** [comment]
Autocomplete support is available from `3.9.0`.

**Comment by dohomi** [comment]
@ChromeGG I think most importantly Storybook should be updated/improved for better documentation. Is there a plugin out which can show all properties a component supports?

**Comment by ChromeGG** [comment]
I have no idea, TBH I'm not soo familiar with Storybook. To be more descriptive on Storybook, we can use `.mdx` files. Unfortunately, I'm very busy this weekend. I can make some research next week.
