### ISSUE TITLE
Autocomplete not returning complete object but only returns "id"

### ISSUE THREAD

**Issue by adityatyagi** [dohomi/react-hook-form-mui#65]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

According to [this](https://codesandbox.io/s/mui-autocomplete-with-react-hook-form-qedgr?file=/src/Countries.js:1116-1128) codesandbox, we are able to return complete object as value for autocomplete, using:
```
onChange={([event, data]) => {
        return data;
      }}
```  

The current implementation of autocomplete:
1. Prohibits to have any data set without an `id` key. If we do not have an `id` key, then the the autocomplete label does not hold value. It resets `onBlur`
2. Because of [this](https://github.com/dohomi/react-hook-form-mui/blob/master/src/AutocompleteElement.tsx#L75), if I want to return a complete object for AutoComplete, I am not able to and it returns `id`.
3. We cannot add an `onChange` on the controller like we can in the codesandbox

### Expected behavior 🤔

We should be able to add `onChange` on the controller wrapping the autocomplete or we should be able to return complete object from the autocomplete without label getting reset on `onBlur`

### Steps to reproduce 🕹

Steps:

Use mock data:
```
export interface IParty {
  id: string;
  name: string;
  address: string;
  gstin: string;
}


const MD_PARTIES: IParty[] = [
  {
    id: '1',
    name: 'APEX PVT. LTD.',
    address:
      'ABCD',
    gstin: '1234'
  },
  {
    id: '2',
    name: 'IE AUTO PVT. LTD.',
    address: 'EFGH',
    gstin: '5678'
  },
];

  /**
   * Autocomplete prop
   * @description uses "name" key from the object as the autocomplete option label
   */
  const autoCompleteProps = {
    getOptionLabel: (option: IParty) => option.name
  };
  
 <AutocompleteElement
              label="Party"
              name="party"
              autocompleteProps={autoCompleteProps}
              options={MD_PARTIES}
            />
```

**Comment by dohomi** [comment]
@adityatyagi you have the full object with your own onChange handler:
```ts
<AutocompleteElement autocompleteProps={{onChange: (_event, value) => console.log(value)}} />
```
I am happy to review any PR if you want to add additional features into the AutocompleElement
