### ISSUE TITLE
Default labelkey and options prop type definitons for SelectElement do not match

### ISSUE THREAD

**Issue by michaelreaton** [dohomi/react-hook-form-mui#66]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

must specify labelkey='title' on SelectElement if I use the { id: string | number, title: string | number }[] type defined for options 

### Expected behavior 🤔

default labelkey should match the options prop definition for SelectElement

**Comment by dohomi** [comment]
Fixed with latest release
