### ISSUE TITLE
Add Storybook Storysource Addon

### ISSUE THREAD

**Issue by ChromeGG** [dohomi/react-hook-form-mui#67]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

As a developer, I want to see the code directly from the storybook.

### Examples 🌈

We can use this addon:
https://storybook.js.org/addons/@storybook/addon-storysource

I can do it on Sunday or next week 😄

**Comment by dohomi** [comment]
After moving to Storybook v7 this needs to be revisited
