### ISSUE TITLE
Start using `.mdx` files to be more descriptive in stories

### ISSUE THREAD

**Issue by ChromeGG** [dohomi/react-hook-form-mui#68]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

MDX is a more robust format for documentation. With this, we can easily describe what the component does and add a link to MUI/RHF documentation.

### Examples 🌈

See:
https://storybook.js.org/docs/react/writing-docs/mdx

I can do it on Sunday or next week 😄

**Comment by dohomi** [comment]
sounds great! I'll try to join next week this week is very busy for me

**Comment by ChromeGG** [comment]
@dohomi  I did some progress with transforming `.tsx` stories to `.mdx` stories. You can track progress #72 

![image](https://user-images.githubusercontent.com/39050595/178149715-29b44a49-1e4f-4ab2-a707-9240ff8d6a9c.png)


Btw. I found sth interesting. You were asking about this. There are two plugins that could help us. Take a look [here](https://storybook.js.org/docs/react/api/argtypes#automatic-argtype-inference)

**Comment by dohomi** [comment]
After moving of v7 of storybook I will try to improve it differently.
