### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by szado** [dohomi/react-hook-form-mui#69]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Thanks for this helpful library.
It would be great if it was possible to translate the standard error messages for validation rules (`required` and for `email` field type). Currently it can be done only with passing own validation config object to all component instances or by overriding all components code.

### Examples 🌈

New property for `FormContainer` which could receive default error messages or other way to declare them would be appreciated.

**Comment by alexcunha** [comment]
Guys, how about creating a context API with an initial state containing the English translation. Anyone who needs to use i18n in their project can add the provider at the top level of the main project component and dispatch the translation when it changes

**Comment by dohomi** [comment]
Error provider is introduced in 5.16.x onwards, simple setup is shown as 
https://react-hook-form-material-ui.vercel.app/?path=/story/textfieldelement--with-form-error-provider
