### ISSUE TITLE
Reformat repo using eslint rools

### ISSUE THREAD

**Issue by ChromeGG** [dohomi/react-hook-form-mui#70]
Currently, eslint is throwing a lot of obvious errors like:
![image](https://user-images.githubusercontent.com/39050595/177855808-15393d92-6a15-4723-a9af-4246dc6d1655.png)

They're easy to fix (most of them are auto-fixable). But the diff will be huuuuge. That's why I want it in a separate issue.

So on this ticket, I'll:
1. Add sonarJS plugin for eslint.
2. Fix all eslint errors.
3. (Optionally) Provide a GH action that runs eslint before merging to master.

@dohomi Let me know what you think about that. If you wanna provide some other eslint rules, feel free 😃

**Comment by dohomi** [comment]
@ChromeGG feel free to open a PR with different eslint settings.
