### ISSUE TITLE
Styled components application

### ISSUE THREAD

**Issue by RhysOnlyBetter** [dohomi/react-hook-form-mui#73]
I'm trying to apply styles to both the SelectElement and MultiSelectElement components, and I've noticed that in multiselects, the root styles are applied to the .MuiInputBase-root rather than the .MuiFormControl-root with the select component. This means that it's difficult to apply styling to the label since it's not a decedent.

I've made a codesandbox with what I'm trying to achieve here: https://codesandbox.io/s/condescending-tereshkova-pvtz6o?file=/src/App.js 

Are there any workarounds I can use here? Apologies if this is a dumb question, I'm relatively new to styled components & react in general.

**Comment by dohomi** [comment]
@RhysOnlyBetter you can also provide `sx` props. This package is not doing anything specific in terms of styling the MUI components, so you might better check inside of the MUI website for answers. Otherwise you can also play around with the AutocompleteElement which has a multiple option as well

**Comment by dohomi** [comment]
I am happy to review a PR. The best would be most likely to add a new prop `formControl` to forward any props for that element.

**Comment by Elvincth** [comment]
THe checkbox element is still missing the FormControl styling option
