### ISSUE TITLE
Custom 'required' for simple SelectElement (+ MultiSelectElement on storybook broken)

### ISSUE THREAD

**Issue by F1r3Hydr4nt** [dohomi/react-hook-form-mui#74]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I suspected that the rules={...} prop would work for the SelectElement but it does not seem to?

There is no example for a custom 'required' on the [storybook](https://react-hook-form-material-ui.vercel.app/?path=/docs/selectelement--required), and the MultiSelectElement does not seem to run either.

Also might you know the best way to programmatically clear form element values to re-trigger the requirement error?

Thanks

**Comment by dohomi** [comment]
@F1r3Hydr4nt what do you mean by "custom required"? You usually just set the required prop to true and thats all you need to do

otherwise you can provide a `validation` object which is an alias for `rules`.

To reset a form have a look at the reset button:
https://github.com/dohomi/react-hook-form-mui/blob/master/src/ResetFormButton.tsx

**Comment by F1r3Hydr4nt** [comment]
Great thanks, I didn't see anything about that validation object in the docs.

Another thing I note is the autocomplete lacks an onChange, will open a PR shortly if I overcome it.

Thank you again

**Comment by F1r3Hydr4nt** [comment]
Turns out you can give the AutoCompleteElement an onChange callback via the autocompleteProps:{onChange:(e)=>{console.log('onChange',e)}} argument, please forgive me

**Comment by F1r3Hydr4nt** [comment]
@dohomi Hello again, is it possible to get a handle on the form 'reset' function outside of the FormContainer context?

An autocomplete selection drives the options of a second select component, and once a change is made in the first, the second's selection needs to be cleared.

**Comment by dohomi** [comment]
@F1r3Hydr4nt you can have a submit button and use the `<button form="yourFormId>"` and add `yourFormId` as an id to your form.

**Comment by F1r3Hydr4nt** [comment]
Is there an example of this anywhere? I note that the FormContainer can be passed a formContext, which I assume would reveal handles for all of the react-hook-form methods outside of it.

**Comment by F1r3Hydr4nt** [comment]
[Aha](https://github.com/dohomi/react-hook-form-mui/blob/af5884deafd0410dbfff685211bc88773af8fb0e/stories/FormContainer.stories.tsx#L45), never mind. Thanks

**Comment by F1r3Hydr4nt** [comment]
It seems that de-connects the error hooks and other things unfortunately,  gonna just check if the components can work without the FormContainer

**Comment by dohomi** [comment]
you can totally work without the FormContainer if you need more specific functionality. I personally use the FormContainer only for simple forms like login / register. As soon I need more deeper logic of the form context I just wire up the form tag myself and use `control` prop on all form components
