### ISSUE TITLE
cannot call api

### ISSUE THREAD

**Issue by sivavj** [dohomi/react-hook-form-mui#75]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

in autocomplete element cannot call api values.

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

**Comment by dohomi** [comment]
I don't know what you are looking for. Can you show it with a codegen?

**Comment by dohomi** [comment]
Closing it as there hasn't been any update on a detailed description
