### ISSUE TITLE
form reset after submit

### ISSUE THREAD

**Issue by BernardMasika** [dohomi/react-hook-form-mui#76]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] I have tested the latest version

### Summary 💡

that after submit event is detected, a form should empty all its fields.

### Examples 🌈

```tsx
const onSubmit = (data) => {
        console.log(data)
        reset()        // example calling method to reset form
    }
```

**Comment by dohomi** [comment]
If you are handling the form by your self you can call reset when ever you like. 

Here is an example in Storybook: **https://github.com/dohomi/react-hook-form-mui/blob/master/stories/FormContainer.stories.tsx#L45**

**Comment by BernardMasika** [comment]
still cannot reset, even after following the example above closely, below is my code! 

```tsx
const LoginComponent = () => {
const formContext = useForm<{ email }> // removed the types because am not writing on tsx
    ({
        defaultValues: {
            email: ' '
        }
    })

return (
<FormContainer  noValidate  formContext={formContext}  onSuccess={data => console.log(data)}>

                            <TextFieldElement
                                variant="outlined"
                                margin="normal"
                                required
                                type={'email'}
                                fullWidth
                                id="email"
                                placeholder="Email Address"
                                name="email"
                                autoComplete="email"
                                autoFocus
                                label={'Email'}
                            />
    </FormContainer>
)}
```
still facing the following error..

![image](https://user-images.githubusercontent.com/50598183/180287292-d134a6e4-24f2-4d13-91dd-56174f4735f7.png)

i am failing to know why the reference issue!

many thanks!

**Comment by BernardMasika** [comment]
figured out the issue after few days!, 

the implementation above and in the referred example is based on typescript! so i removed the type on useForm hook and reset the form as shown below.

```tsx
const formContext = useForm({
        defaultValues: {
            email: '',
            password: ''
        }
    });

    const handleSubmit = (data) => {
        console.log(data)
        formContext.reset()
    }

```
