### ISSUE TITLE
[ERROR] Could not resolve "@mui/x-date-pickers/DatePicker"

### ISSUE THREAD

**Issue by samuelcastro** [dohomi/react-hook-form-mui#79]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Getting the following error when building the application:

```
[ERROR] Could not resolve **"@mui/x-date-pickers/DatePicker"**
```

### Expected behavior 🤔

No errors

### Steps to reproduce 🕹

Steps:

1. Install the library
2. Build the project

**Comment by dohomi** [comment]
please check your npm log, you are missing peerDependencies which needs to be installed on your side. @mui/x-date-pickers is one of them if you are using datepickers

**Comment by HugoGresse** [comment]
Sorry to update a closed issue. 
I add the same issue on a new project, I was not using MUI DatePickers, and did not understand as stated in the readme that the DatePickers needed to be installed even if we are not using it: "This package utilizes pickers and icons of the MUI ecosystem. If you make use of it add them to your app." 
Is it a regression? 


```
5:19:42 PM [vite] error while updating dependencies:
Error: Build failed with 3 errors:
node_modules/react-hook-form-mui/dist/esm/index.js:1:1594: ERROR: Could not resolve "@mui/x-date-pickers/DatePicker"
node_modules/react-hook-form-mui/dist/esm/index.js:1:2471: ERROR: Could not resolve "@mui/x-date-pickers/DateTimePicker"

```

**Comment by dohomi** [comment]
@HugoGresse there seem to be some bundlers which are required them to be part of your package.json. Its safe to add them, if you don't use any picker related component you won't have them in your bundle size, but it seems necessary to keep `@mui/x-date-pickers` as part of your package.json

**Comment by Chen-913** [comment]
I have the same problem. Adding more dependencies may make me feel uncomfortable😥
