### ISSUE TITLE
Can not find utils in context [workaround]

### ISSUE THREAD

**Issue by ajoslin103** [dohomi/react-hook-form-mui#8]
This is great work, and coming in at Just The Right Time (!!) as I struggle with using Material UI with react-hook-forms !

So I'm trying to use your DatePickerElement, and I get the error: `Can not find utils in context`

Looking thru your stories and files I see that your DatePickerElement seems to depend on being wrapped in your DateDayjsProvider (which you don't export for me to use...)

So I copied your DateDayjsProvider & added it myself

I then got errors about @date-io/dayjs & dayjs -- which I installed

Then I got an error `utils.getYearText is not a function`

Googling that took me here: https://github.com/mui-org/material-ui-pickers/issues/1442

So I downgraded to @date-io/dayjs@1.x and now things work!

Thanks for your very timely work -- it's going to help this project to arrive on time !!

```
// https://material-ui.com/components/switches/
import { Box, Button } from '@material-ui/core'

// https://www.npmjs.com/package/react-hook-form-mui
import { FormContainer, TextFieldElement, DatePickerElement } from 'react-hook-form-mui'

// copied from inside 'react-hook-form-mui'
import DateDayjsProvider from './DateDayjsProvider'

export const FormEventNew = ({ onSubmit, submitName }
  : { onSubmit: (values: any) => void, submitName: string }) => {

  return (
    <DateDayjsProvider>
      <FormContainer
        defaultValues={{ name: '', date: '' }}
        onSuccess={onSubmit}
      >
        <TextFieldElement name="name" label="Event Name" required />

        <DatePickerElement
          label={'Event Date'}
          name={'required-date-picker'}
          required
        />

        <br />

        <Box>
          <Button variant="contained" color="primary" type="submit">
            {submitName}
          </Button>
        </Box>

      </FormContainer>
    </DateDayjsProvider>
  )
}
```

**Comment by dohomi** [comment]
I don't provide a date provider for the picker myself. The main issue is that v1 was not able to code split correctly. 

Just wrap your form with `MuiPickersUtilsProvider`and you are ready to go. I realized that Dayjs is not as stable as date-fns but its up to you.
Follow this guide to wrap the form with your provider: https://material-ui-pickers.dev/localization/date-fns

**Comment by ajoslin103** [comment]
thanks !!  you are doing great work !!

If I go back and re-wrap I'll post it here for others to find

**Comment by dohomi** [comment]
I updated the Storybook to showcase both Providers. https://github.com/dohomi/react-hook-form-mui#with-datepicker
Hope this helps thanks for pointing me at it.
