### ISSUE TITLE
Autocomplete ignores `renderOption` prop

### ISSUE THREAD

**Issue by kaitlyn-lighthouse** [dohomi/react-hook-form-mui#85]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If I pass the `renderOption` prop to the `autocompleteProps` of the AutocompleteElement, it is completely ignored.

### Expected behavior 🤔

Passing the `renderOption` prop should override any other logic for rendering options.

**Comment by dohomi** [comment]
Resolved in 5.3.2
