### ISSUE TITLE
TextFieldElement doesn't allow defaultValue to be set.

### ISSUE THREAD

**Issue by paales** [dohomi/react-hook-form-mui#92]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

We should probably expose the defaultValue from the ControllerProps instead of the one from the TextInput and apply it to the Controller

```
export type TextFieldElementProps<T extends FieldValues = FieldValues> = Omit<
  TextFieldProps,
  'name' | 'defaultValue'
> & {
  validation?: ControllerProps['rules']
  parseError?: (error: FieldError) => string
} & Pick<ControllerProps<T>, 'control' | 'defaultValue' | 'name'>
```

If you don't get around to it, I'll try and create a PR.

**Comment by paales** [comment]
@dohomi react-hook-form supports this natively, see Controller docs: https://react-hook-form.com/api/usecontroller/controller

We're build a product add to cart form:

- We call useForm at a high level and create a context for it.
- In a different part of the system we add fields that is dependent on the product type that is being loaded: `<BundleProductOptions/>` / `<ConfigurableProductOptions/>` / `<DownloadableProductOptions/>`

Exampe of the structure we're using

```tsx
function ProductPage() {
  const product: ProductInterface = { __typename: 'bla', other: 'fields' }

  return (
    <AddProductsToCartForm uid={product.uid}>
      {isTypename(product, ['ConfigurableProduct']) && <ConfigurableProductOptions />}
      {isTypename(product, ['BundleProduct']) && <BundleProductOptions />}
      {isTypename(product, ['DownloadableProduct']) && <DownloadableProductOptions />}
    </AddProductsToCartForm>
  )
}
```

Inside Configurable/Bundle/Downloadable we've got fields and some of them have a defaultValue, we'd like to set this through the react-hook-form Controller's defaultValue

**Comment by dohomi** [comment]
@paales yes thats what the defaultValues of `useForm` are doing. If you check the Storybook you see that you can set the defaultValues on the form hook. It sets the defaultValue on each controller of each field. 
https://react-hook-form-material-ui.vercel.app/?path=/story/textfieldelement--pre-defined

Or am I misunderstanding something? You'd set on the useForm hook the default values and it should be passed in. If you have different requirement either set up a codegen or pass a PR I am happy to have a look

**Comment by paales** [comment]
@dohomi I'll try and create a PR, I think it is a fairly small change :)
