### ISSUE TITLE
Broken components name in storybook

### ISSUE THREAD

**Issue by ChromeGG** [dohomi/react-hook-form-mui#93]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

All components in the storybook have broken names:
![image](https://user-images.githubusercontent.com/39050595/190904962-d5623d84-eb06-4695-ba9d-6372679c626f.png)

### Expected behavior 🤔

Components name should be visible

### Steps to reproduce 🕹

Steps:

1. Go to https://react-hook-form-material-ui.vercel.app/?path=/docs/radiobuttongroup--basic
2. Open any code snippet

**Comment by dohomi** [comment]
that is very strange.. https://github.com/dohomi/react-hook-form-mui/blob/master/apps/storybook/stories/AutocompleteElement.stories.tsx the source code for sure uses full names, it seems to be some internal Storybook where they use short names for all the docs.. I need to see how to change it

**Comment by dohomi** [comment]
Finally found the time to fix this issue. All names should be readable in the Storybook
