### ISSUE TITLE
Provide a way to disable FormHelperText on SelectElement

### ISSUE THREAD

**Issue by benjaminchardin2** [dohomi/react-hook-form-mui#94]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

When using SelectElement if an error is detected a FormHelperText element is automatically displayed. 
In my team's project, we wrote a HOC that is in charge of displaying errors, and because of this behavior two FormHelperText are displayed.

Currently, I found a hacky way of not displaying the FormHelperText by passing the following parseError `parseError={() => ''}` 

Could it be possible to provide a props to disable the HelperText?

Thanks in advance for reading!

**Comment by dohomi** [comment]
I'm not thinking that passing an empt error message is a `hacky` way, it is exactly the way how you should handle your use case.

**Comment by benjaminchardin2** [comment]
Ok thanks for your help !

I’lol close the issue
