### ISSUE TITLE
Support for TimePicker

### ISSUE THREAD

**Issue by FlorianCassayre** [dohomi/react-hook-form-mui#95]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

MUI has a [`TimePicker`](https://mui.com/x/react-date-pickers/time-picker/) component, it would be great if this library would support it as well (e.g. `TimePickerElement`).

**Comment by dohomi** [comment]
I'm currently stuck in a project, but happy to review a PR for this component.
