### ISSUE TITLE
Support ZOD as Frontend Validation Schema

### ISSUE THREAD

**Issue by DaRabus** [dohomi/react-hook-form-mui#97]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

To support a Frontend Validaiton Service we have to pass the props into the "FormContainer"

https://github.com/colinhacks/zod

If you agree that this could be useful, I will create a PR for you for the integration :)

**Comment by dohomi** [comment]
@DaRabus I use `superstruct` in one of my projects, but for sure `zod` will work in the same way. Feel free to open a PR I currently just don't use `FormContainer` and pass the `control` prop to each element.

**Comment by DaRabus** [comment]
Thanks for the advice.

I will use it like this, when I'll get some time I may add a PR for properly typing the resolver, so other people see it directly how to pass it :)

My bad i didn't see it directly.

**Comment by dohomi** [comment]
If I find time I will add an example to the stories where `zod` is used.

**Comment by rjborba** [comment]
Hey, great lib by the way @dohomi . 

I've got a followup question regarding Zod support: is it possible to make field name property typesafe on the actual component?

**Comment by dohomi** [comment]
@rjborba yes you can use any plugin for react-hook-form, have a look at this example: https://github.com/dohomi/react-hook-form-mui/blob/master/apps/storybook/stories/FormContainer.stories.tsx#L129
this is already typesafe, but you can also use any plugin with `useForm`

**Comment by sKopheK** [comment]
i find docs in the storyboard missing a lot information, e.g. `StrictTypingForm` does not even include `FormContainer` there. i love the idea behind the library, but i'm afraid it comes with a lot of limitations that usage of rhf and mui separately does not have

**Comment by dohomi** [comment]
> i find docs in the storyboard missing a lot information, e.g. `StrictTypingForm` does not even include `FormContainer` there. the biggest downside is, there is not a full API docs. i love the idea behind the library, but i'm afraid it comes with a lot of limitations that usage of rhf and mui separately does not have

You can use part of this library, or you just take inspiration on how to wrap up your own components. There is no bullet proof way, this library just wraps most form components of MUI into `useController` of RHF. There isn't too much magic involved. You can use the `FormContainer` in the same way: you provide the FormContext for all forms via provider. If you don't wish to use a provider, you can use this lib without the FormContainer and provide `control` to each FormElement of this library. 

I hope this makes it more clear, this lib is only a set of components ready to use - for sure with some limitations regarding the full API of MUI or RHF.
