### ISSUE TITLE
eslint and prettier not working in project?

### ISSUE THREAD

**Issue by mg-chao** [dohomi/react-hook-form-mui#99]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

When I try to edit the code, eslint or pretter show many errors.
Code should be formatted

### Examples 🌈

[DateTimePickerElement.tsx](https://github.com/dohomi/react-hook-form-mui/blob/master/packages/rhf-mui/src/DatePickerElement.tsx) `indentation of 2 spaces but found 84.eslint[indent](https://eslint.org/docs/rules/indent)`

**Comment by dohomi** [comment]
I did not see any issue with eslint so far.
